Lang <-
{
	/* scripts/Classes/CPlayer.nut */
	AutoLogged							= [ "You were auto logged." ]
	UIDNotMatchNeedLogin				= [ "Please login into your account with /login" ]
	AccNotExistNeedReg					= [ "Your account does not exist in our database. Please register with /register" ]
	PlayerJoin							= [ "[#ffffff]%s %shas connected from [#ffffff]%s." ]
	PlayerJoin1							= [ "[#ffffff]%s %shas connected." ]
	JoinMsg 							= [ "Welcome to ViceLand, [#ffffff]%s" ]
	HelpMsgJoin							= [ "Use [#ffffff]/cmds %sfor available server command and [#ffffff]/keybinds %sfor available keybinds. You can disable this help message with [#ffffff]/msetting" ]
	VIPExpired 							= [ "Your VIP status has expired." ]
	
	/* scripts/Commands/Account.nut */
	Logged								= [ "You were logged." ]
	PasswordNotLonger					= [ "Password length must contain more than 5 characters." ]
	AlreadyRegistered 					= [ "You are already registered." ]
	WrongPassword						= [ "Wrong password." ]
	AlreadyLogged						= [ "You are already logged in." ]
	PasswordChanged                     = [ "Your password has been changed." ]
	WrongOldPassword                    = [ "You have entered a wrong old password." ]
	NewPasswordNotLonger				= [ "New password length must contain more than 5 characters." ]
	Register 							= [ "You have sucessfully registered." ]
	RegisterSyntax						= [ "Syntax, /register [password]" ]
	LoginSyntax							= [ "Syntax, /login [password]" ]
	ChangepassSyntax					= [ "Syntax, /changepass [old password] [new password]" ]
	Cash								= [ "[#ffffff]%s %sCash [#ffffff]$%s %sCoin [#ffffff]%s" ]
	NotPermissionViewCash				= [ "You do not have permission to view other player's cash." ]
	CashOwn								= [ "Your cash [#ffffff]$%s %sVice Coin [#ffffff]%s" ]
	CantEnterCooldown					= [ "You cannot enter this interior because you are being hit by someone." ]
	BuycoinSyntax						= [ "Syntax, /buycoin [amount]" ]
	SellcoinSyntax						= [ "Syntax, /sellcoin [amount]" ]
	BuyCoin								= [ "You bought [#ffffff]%d Vice Coin. %sCost [#ffffff]%s" ]
	NeedCashBuyCoin						= [ "You need %s to buy Vice Coin" ]
	InvalidAmount						= [ "Amount must be greater than 0." ]
	NotInBank							= [ "You must be in the bank or lobby to use this command." ]
	SellCoin							= [ "You sold [#ffffff]%d Vice Coin %sfor [#ffffff]%s." ]
	NeedCoinToSell						= [ "You need %d Vice Coin to sell." ]
	CoinInfo							= [ "Current price per Vice Coin" ]
	CoinInfo1							= [ "Buy [#ffffff]$%s %sSell [#ffffff]$%s" ]
	BuyCoinExeeded						= [ "You cannot buy more than 100 Vice Coins at once." ]
	SellCoinExeeded						= [ "You cannot sell more than 100 Vice Coins at once." ]

	/* scripts/Events/Player/PlayerKilled.nut */
	KillMessage							= [ "[#ffffff]%s %shas killed [#ffffff]%s%s. [#ffffff][%s] [%s] [%.4fm]" ]
	
	/* scripts/Events/Player/PlayerWasted.nut */
	DeathMessage						= [ "[#ffffff]%s %shas died."]
	DeathMessageSuicide					= [ "[#ffffff]%s %shas commited suicide."]
	
	/* Global */
	TargetNotLogged						= [ "Target player not logged." ]
	TargetNotRegistered					= [ "Target player not registered." ]
	TargetNotOnline						= [ "Target player not connected." ]
	NotRegistered						= [ "You are not registered." ]
	NotLogged							= [ "You are not logged." ]
	InEventCantUseCmd					= [ "You cannot use this command while in event." ]
	InIntCantUseCmd						= [ "You cannot use this command while inside interior." ]
	TargetInEvent						= [ "Target player currently in event." ]
	TargetInInterior					= [ "Target player currently inside interior." ]
	InvalidPlayer						= [ "Target player not connected." ]
	NoPermissionWorldCmd				= [ "You dont have permission to use this command." ]
	HPCooldownCantUseCmd				= [ "You cannot use this command for a while because you are getting hit by someone." ]
	
	/* scripts/Commands/Deathmatch.nut */
	GetwepSyntax						= [ "Syntax, /%s [weapons]" ]
	GetWepCantGetMini					= [ "You cannot obtain minigun on public world." ]
	GetWep								= [ "You received following weapon [#ffffff]%s" ]
	InfoSTarget							= [ "[#ffffff]%s %sstats" ]
	InfoS								= [ "Kills [#ffffff]%s %sDeaths [#ffffff]%s %sRatio [#ffffff]%.2f %sHighest killing streak [#ffffff]%d" ]
	InfoS1								= [ "Register date [#ffffff]%s %sJoins [#ffffff]%d %sTotal playtime [#ffffff]%s %sXP [#ffffff]%s/%s %sLevel [#ffffff]%s" ]
	InfoSSelf							= [ "Your stats" ]
	InfoThis							= [ "[#ffffff]%s %scurent session stats" ]
	InfoThisS							= [ "Kills [#ffffff]%s %sDeaths [#ffffff]%s %sKill streak [#ffffff]%d" ]
	InfoThisS1							= [ "Play time [#ffffff]%s" ]
	InfoThisSelf						= [ "Your current session stats" ]
	GetWepNotExist						= [ "Given weapon does not exist." ]
	SpawnwepSyntax						= [ "Syntax, /spawnwep [weapons]" ]
	SpawnMinWarn						= [ "Please note, Minigun can only be used in a private world." ]
	GetSpawnwep							= [ "Following weapons have been added to spawn weapon [#ffffff]%s" ]
	Disarm								= [ "Sucessfully disarmed." ]
	Healing								= [ "Healing in process. Please do not move." ]
	HealSucess							= [ "Sucessfully healed. Cost [#ffffff]%s" ]
	HealFailedMove						= [ "Healing failed because you move." ]
	NeedCashToHealth					= [ "You need $%s to heal yourself." ]
	HealingInProcess					= [ "Healing already in process." ]
	HealALreadyFull						= [ "You are at full health." ]
	ArmSucess 							= [ "You equipped an armour." ]
	ArmFailedMove 						= [ "You failed to equip an armour because you moved." ]
	ArmALreadyFull 						= [ "Your armour value is already full." ]
	Armoring 							= [ "Equipping armour, please do not move." ]

	/* scripts/Miscs/Deathmatch.nut */
	KillReward							= [ "You killed [#ffffff]%s %swith weapon [#ffffff]%s. %s Distance [#ffffff]%.4fm %sReward [#ffffff]%s %sand [#ffffff]%s XP" ]
	Killed								= [ "[#ffffff]%s %shas killed you with [#ffffff]%s. %sDistance [#ffffff]%.4fm %sLose [#ffffff]$%s" ]
	OnSpree								= [ "[#ffffff]%s %sis on killing streak of [#ffffff]%d." ]
	OnSpreeSelf							= [ "You are now on a killing streak on [#ffffff]%d. %sReward [#ffffff]%s %sand [#ffffff]%s XP" ]
	EndSpree							= [ "[#ffffff]%s %shas ended [#ffffff]%s %skilling streak of [#ffffff]%d." ]
	EndSpreeSelf						= [ "You ended [#ffffff]%s %skilling streak of [#ffffff]%d. %sReward [#ffffff]%s %sand [#ffffff]%s XP" ]
	EndSpreeSelf1						= [ "[#ffffff]%s %shas ended their own killing streak." ]
	
	/* scripts/Commands/Location.nut */
	SpawnlocSyntax						= [ "Syntax, /spawnloc [set/off/location name]" ]
	GotolocSyntax						= [ "Syntax, /gotoloc [location name]" ]
	LocinfoSyntax						= [ "Syntax, /locinfo [location name]" ]
	SavelocSyntax						= [ "Syntax, /saveloc [location name]" ]
	Spawnloc							= [ "Sucessfully set your spawn location. Cost [#ffffff]$%s" ]
	SpawnlocWarning						= [ "Warning, use this feature at your own risk." ]
	NeedCashToSpawn						= [ "You need $%s to use this feature." ]
	SpawnlocOff							= [ "You disabled your spawn location." ]
	SpawnlocAlreadyOff					= [ "Spawn location currently disabled." ]
	SpawnlocLoc							= [ "Sucessfully set spawn at [#ffffff]%s. %sCost [#ffffff]%s" ]
	Gotoloc								= [ "You will teleport to that location in 3 seconds. Please no not move." ]
	GotolocAll							= [ "[#ffffff]%s %steleported to [#ffffff]%s. %sCost [#ffffff]%s" ]
	GotolocSucess						= [ "Sucessfully teleported to [#ffffff]%s. %sCreator [#ffffff]%s %sCost [#ffffff]%s" ]
	TeleportFailMove					= [ "Teleport failed because you moved." ]
	NeedCashToGotoloc					= [ "You need $%s to teleport." ]
	LocationNotExist					= [ "Given location does not exist." ]
	AlreadyTeleporting					= [ "Teleport already in process." ]
	Saveloc								= [ "Location [#ffffff]%s %ssaved. Cost [#ffffff]%s" ]
	LocationExist						= [ "Given location already exist." ]
	LocInfo								= [ "Location [#ffffff]%s %sCreator [#ffffff]%s %sCreated date [#ffffff]%s %sCost needed to teleport [#ffffff]%s" ]
	Goto								= [ "You will teleport to target player in 3 seconds. Please no not move." ]
	GotoAll								= [ "[#ffffff]%s %steleported to [#ffffff]%s. %sCost [#ffffff]%s" ]
	GotoSucess							= [ "Sucessfully teleported to [#ffffff]%s. %sCost [#ffffff]%s" ]
	TeleportFailTargetNotExist			= [ "Teleport failed because target player is not online." ]
	GotoTargetSameAsPlayer				= [ "You cannot teleport to yourself." ]
	GotoSyntax							= [ "Syntax, /goto [player]" ]	
	GotoLobby							= [ "You will be teleport to the lobby in 3 seconds. Please don't move." ]
	GotoLobbyAll						= [ "[#ffffff]%s %shas teleported to lobby." ]
	TargetOnLockedWorld					= [ "Target player is on locked world." ]
	TargetAdminDuty 					= [ "Target player is currently on admin duty." ]
	TargetDisallowTP 					= [ "Target player has disallowed teleport." ]

	/* scripts/Events/Player/PlayerRequestSpawn.nut */
	NoLoggedSpawn						= [ "Please login into your account first." ]
	NoRegisterSpawn						= [ "Please register your account first." ]

	/* scripts/Commands/World.nut */
	WorldInvalidWorld					= [ "You must be in a private world(2000-4000/5000-10000) to use this command." ]
	WorldNoPermission					= [ "You do not have permission to use this command." ]
	WorldNotSameWorld					= [ "Target player is not in the same world as yours." ]
	WorldSettingSyntax1					= [ "Syntax, /worldsetting [type/name/welcomemsg/spawn/worldkill/driveby/ping/fps] [value]"]
	WorldKickSyntax1					= [ "Syntax, /worldkick [player] [reason]" ]
	WorldBanSyntax1						= [ "Syntax, /worldban [player] [reason]" ]
	WorldUnbanSyntax1					= [ "Syntax, /worldunban [player]" ]
	WorldSetlevelSyntax1				= [ "Syntax, /worldsetlevel [player] [level]" ]
	WorldPermissionSyntax1				= [ "Syntax, /worldpermission [setworldname/setworldmessage/setworldtype/setworldspawn/worldkick/worldban/worldunban/setworldname/worldsetlevel/mapping/vehspawning/vehmanage/worldkill/worldann/worldsetlevelcmd/setfpspinglimit] [level]" ]
	WorldAnnSyntax1						= [ "Syntax, /worldann [all/player] [text]" ]
	WorldGotoSyntax1					= [ "Syntax, /gotoworld [main/world id]" ]
	WorldInfoSyntax1					= [ "Syntax, /worldinfo [world]" ]
	WorldOwnWorld						= [ "You purchased this world." ]
	WorldAlreadyHasOwner				= [ "This world already has an owner." ]
	WorldSetName						= [ "You changed world name to [#ffffff]%s." ]
	WorldSetWelcomeMessageRemove		= [ "You disabled world welcome message." ]
	WorldSetWelcomeMessage				= [ "You changed world welcome message to [#ffffff]%s." ]
	WorldSetWelcomeMessageSyntax		= [ "Syntax, /worldsetting welcomemsg [text/none]"]
	WorldSetSpawn						= [ "You changed world spawn. All players will spawn here when they enter this world." ]
	WorldKillOff						= [ "[#ffffff]%s %shas disabled killing in this world." ]
	WorldkillOffAdmin					= [ "You disabled killing in this world." ]
	WorldKillOn							= [ "[#ffffff]%s %shas enabled killing in this world." ]
	WorldkillOnAdmin					= [ "You enabled killing in this world." ]
	WorldkickAll						= [ "[#ffffff]%s %shas kicked all players in this world." ]
	WorldkickNotice						= [ "You has been kicked from world [#ffffff]%d" ]
	WorldkickAllAdmin					= [ "You kicked all players in this world." ]
	WorldkickAllNoPlayer				= [ "There is no available player/s to kick." ]
	WorldkickAnn						= [ "[#ffffff]%s %shas kicked [#ffffff]%s %sfrom the world. Reason [#ffffff]%s"]
	WorldkickAdmin						= [ "You kicked %s %sfrom this world with reason [#ffffff]%s" ]
	WorldkickWithoutReason				= [ "[#ffffff]%s %shas kicked [#ffffff]%s %sfrom the world." ]
	WorldkickAdminWithoutReason			= [ "You kicked [#ffffff]%s %sfrom this world." ]
	WorldbanAnn							= [ "[#ffffff]%s %shas banned [#ffffff]%s %sfrom the world. Reason [#ffffff]%s."]
	WorldBanAdmin						= [ "You banned [#ffffff]%s %sfrom this world with reason [#ffffff]%s." ]
	WorldbanWithoutReason				= [ "[#ffffff]%s %shas banned [#ffffff]%s %sfrom the world." ]
	WorldBanAdminWithoutReason			= [ "You banned [#ffffff]%s %sfrom this world." ]
	WorldbanNotice						= [ "You has been banned from world [#ffffff]%d." ]
	WorldUnban							= [ "[#ffffff]%s %sunbanned [#ffffff]%s %sfrom this world." ]
	WorlunbanAdmin						= [ "You unbanned [#ffffff]%s %sfrom this world." ]
	WorldunbanNotice					= [ "You has been unbanned from world [#ffffff]%d." ]
	WorldUnbanPlrNotBanned				= [ "Target player is not banned." ]
	WorldSetlevel						= [ "[#ffffff]%s %shas set [#ffffff]%s %sworld level to [#ffffff]%d." ]
	WorldsetlevelAdmin					= [ "You set [#ffffff]%s %sworld level to [#ffffff]%d." ]
	WorldsetlevelNotice					= [ "You level is setted to [#ffffff]%d." ]
	WorldLevelNotValid					= [ "Level must between 0 and 1000000." ]
	Worldsetlevelcmd					= [ "You changed permission [#ffffff]%s %sto [#ffffff]%d." ]
	WorldlockOffAll						= [ "[#ffffff]%s %shas unlocked this world." ]
	WorldlockOff						= [ "You unlocked this world." ]
	WorldlockOnAll						= [ "[#ffffff]%s %shas locked this world." ]
	WorldlockOn							= [ "You locked this world." ]
	WorldAnnAllAdmin					= [ "You sending announcement [#ffffff]%s %sto all player in this world." ]
	WorldAnnAdmin						= [ "You sending announcement [#ffffff]%s %sto [#ffffff]%s." ]
	WorldNoOwnerCanClaim				= [ "You can purchase this world with /buyworld" ]
	WorldWelcomeMessage					= [ "[#ffffff]%s" ]
	WorldSameWorld						= [ "You already on this world." ]
	WorldCantEnterBanned				= [ "You are banned from target world." ]
	WorldIsLocked						= [ "Target world is locked." ]
	WorldInfo1							= [ "World [#ffffff]%d %sOwner [#ffffff]%s %sName [#ffffff]%s" ]
	WorldInfo2							= [ "Locked [#ffffff]%s %sAllow killing [#ffffff]%s %sAllow drive by [#ffffff]%s %sType [#ffffff]%s" ]
	WorldInfo3							= [ "World admin [#ffffff]%s %sFPS/Ping kick system [#ffffff]%s"]
	WorldInfo4							= [ "Welcome message [#ffffff]%s" ]
	WorldInfo5							= [ "Min. FPS [#ffffff]%s %sMax. Ping [#ffffff]%s" ]
	WorldTypeAlreadyStunt				= [ "This world already on stunt mode." ]
	WorldTypeAlreadyNormal				= [ "This world already on normal mode." ]
	WorldChangeType						= [ "You changed world type to [#ffffff]%s." ]
	WorldTypeSyntax						= [ "Syntax, /worldsetting type [normal/stunt]" ]
	WorldNoWorldAdmin					= [ "This world dont have world admin feature." ]
	GotoWorld							= [ "Switching to target world in 3 seconds. Please do not move." ]
	GotoworldAll						= [ "[#ffffff]%s %shas switched to world [#ffffff]%d." ]
	GotoWorldSucess						= [ "Sucessfully switched to world [#ffffff]%d." ]
	WorldSwitchFailMove					= [ "World switch failed because you move." ]
	WorldCantBuy						= [ "You need at least %s Vice Coin to purchase world." ]
	GotoworldAllPublic					= [ "[#ffffff]%s %shas switched to public world." ]
	GotoWorldSucessPublic				= [ "Sucessfully switched to public world." ]
	WorldIDNotNum						= [ "World ID must be in integer." ]
	WorlddbOff							= [ "[#ffffff]%s %shas disabled drive by in this world." ]
	WorlddbOffAdmin						= [ "You disabled drive by in this world." ]
	WorlddbOn							= [ "[#ffffff]%s %shas enabled drive by in this world." ]
	WorlddbOnAdmin						= [ "You enabled drive by in this world." ]
	WorldPermissionSyntax2				= [ "Syntax, /worldpermission2 [goto/gotoloc/heal/wep/spawnloc/canattack/candriveby/enterworld] [level]" ]
	WorldFPSSet							= [ "[#ffffff]%s %shaa changed FPS limit to [#ffffff]%d." ]
	WorldFPSSelf						= [ "You changed world FPS limit to [#ffffff]%d." ]
	WorldValueNotCorrect				= [ "Value must between 0 and 60." ]
	WorldFPSValueNotNum					= [ "Value must be in integer." ]
	WorldSetFpsSyntax					= [ "/worldsetting fps [value/0 = off]" ]
	WorldPingSet						= [ "[#ffffff]%s %shaa changed Ping limit to [#ffffff]%d." ]
	WorldPingSelf						= [ "You changed world Ping limit to [#ffffff]%d." ]
	WorldPingValueNotCorrect			= [ "Value must between 0 and 60000." ]
	WorldSetPingSyntax					= [ "/worldsetting ping [value/0 = off]" ]
	WorldNoWorldFPS						= [ "This world dont have fps/ping limit feature." ]
	WorldSold							= [ "You sold this world for [#ffffff]%d Vice Coin" ]
	WorldNotOwner						= [ "You are not the owner of this world." ]
	WorldNoNeedMod						= [ "You do not need to purchase extra world feature." ]
	WorldGetLevelIsOwner				= [ "[#ffffff]%s %sis owner of this world." ]
	WorldGetLevel						= [ "[#ffffff]%s %slevel in this world is [#ffffff]%d." ]
	WorldGetLevelIsOwnerSelf			= [ "You are owner of this world." ]
	WorldGetLevelSelf					= [ "Your level in this world is [#ffffff]%d." ]
	WorldIsPublic						= [ "This is public world. Type [#ffffff]%s" ]
	WorldCantSelf						= [ "You cannot use this command on yourself." ]
	WorldCannotUseOnHigh				= [ "You cannot use this command on target with higher or same level as you." ]
	WorldSetNameSyntax1					= [ "Syntax, /worldsetting name [text]" ]
	WorldInvalidWorld1					= [ "World id should be integer(1000-4000/5000-10000) or main." ]

	/* scripts/Miscs/World.nut */
	BuyWorld							= [ "You sucessfully purchased world [#ffffff]%d." ]
	NotEnoughBuyWorld					= [ "You need %s Vice Coin to purchase this world." ]
	AlreadyHasOwner						= [ "This world already has owner." ]
	ModWorld							= [ "You purchased World Admin and FPS/Ping limit system for your world for [#ffffff]%s Vice Coin." ]
	ModWorld1							= [ "You purchased %s for [#ffffff]%s Vice Coin." ]
	NotEnoughBuyMod						= [ "You need $%s to purchase additons." ]
	NoWorldModSelected					= [ "You need select at least 1 option." ]
	
	/* scripts/Events/Player/PlayerSpawn.nut */
	WorldMovedNoPermission				= [ "You have been moved to public world because you dont have permission to spawn in private world." ]
	
	/* scripts/Events/Player/PlayerCreated.nut */
	WorldKickDueFPS						= [ "[#ffffff]%s %shas been kicked from the world due to low FPS. [#ffffff]%s" ]
	WorldKickDueToFPS					= [ "You has been kicked from world due to low FPS. [#ffffff]%s" ]
	WorldFPSFinalWarn					= [ "Your FPS is below the limit of [#ffffff]%s, %sfix it or you will be kicked from world. This is your final warning." ]
	WorldFPSFirst						= [ "Your FPS is below the limit of [#ffffff]%s, %sfix it or you will be kicked from world." ]
	WorldKickDuePing					= ["[#ffffff]%s %shas been kicked from the world due to exceeded ping limit. [#ffffff]%s" ]
	WorldKickDueToPing					= [ "You have been kicked from world due to high ping. [#ffffff]%s" ]
	WorldPingFinalWarn					= [ "Your Ping exceeded the limit of[#ffffff]%s, %sfix it or you will be kicked from world. This is your final warning." ]
	WorldPingFirst						= [ "Your Ping exceeded the limit of [#ffffff]%s, %sfix it or you will be kicked from world." ]
	
	/* scripts/Commands/Object.nut */
	ObjAddSyntax						= [ "Syntax, /addobject [model]" ]
	ObjEditSyntax						= [ "Syntax, /editobject [ID]" ]
	ObjFindSyntax						= [ "Syntax, /findobject [radius]" ]
	ObjAddNotInt 						= [ "Object model must be in integer." ]
	ObjEditNotInt						= [ "ID must be in integer." ]
	ObjFindNotInt						= [ "Radius must be in integer." ]
	ObjAdded							= [ "Object added. You are now begin to edit this object. ID [#ffffff]%d" ]
	ObjCurrentEditing 					= [ "You are currently editing something else." ]
	ObjSomeoneEdit						= [ "Someone is currently editing this object." ]
	ObjIDNotFound						= [ "Object ID not found." ]
	ObjFind								= [ "Object found in range [#ffffff]%s" ]
	ObjNotFound							= [ "No object found in placed radius." ]
	ObjEditing							= [ "You are now editing selected object." ]
	
	/* scripts/Events/Player/PlayerKeyPress.nut */
	EditSensPlus						= [ "Your increased edit sens and your value is now [#ffffff]%f." ]
	EditSensMinus						= [ "Your decreased edit sens and your value is now [#ffffff]%f." ]
	ObjDeleted							= [ "Object deleted." ]
	ObjSaved							= [ "Object saved." ]
	ChangeEditType                      = [ "Your edit type now [#ffffff]%s." ]
	ChangeEditTypeTips					= [ "You can use PageUp to increase editsens and PageDown to decrease editsens." ]
	ObjEditing							= [ "You are now editing selected object." ]
	ObjClone							= [ "Object cloned. ID [#ffffff]%d" ]	
	PickupDel							= [ "Pickup deleted." ]
	PickSaved							= [ "Pickup saved." ]
	
	/* scripts/Commands/Pickup.nut */
	AddPickupSyntax						= [ "Syntax, /addpickup [model]" ]
	EditPickupSyntax					= [ "Syntax, /editpickup [ID] [pos/type/level/prop/msg/sound]" ]
	FindPickupSyntax					= [ "Syntax, /findpickup [radius]" ]
	PickupAdd							= [ "Pickup added. ID [#ffffff]%d" ]
	PickupList							= [ "Pickup found in range [#ffffff]%s" ]
	PickupXFind							= [ "Pickup not found." ]
	PickupEditPos						= [ "You are now editing pickup position." ]
	PickupEditType						= [ "You changed pickup type to [#ffffff]%s." ]
	PickupEditTypeSame					= [ "This pickup already %s." ]
	PickupEditMsgDisable				= [ "You disabled pickup message." ]
	PickupEditMsg						= [ "Pickup message has been changed to [#ffffff]%s." ]
	PickupEditMsgSyntax					= [ "Syntax, /editpickup [ID] msg [text/disable]" ]
	DisablePickupSound					= [ "You disabled pickup sound." ]
	PickupEditSound3D					= [ "You added 3D pickup sound [#ffffff]%s" ]
	PickupEditSound2D					= [ "You added pickup sound [#ffffff]%s." ]
	PickupEditSoundSyntax				= [ "Syntax, /editpickup [ID] sound [sound id/disable] [true/false (3D sound)" ]
	PickupEditSoundNotNum				= [ "Sound ID must be in integer." ]
	PickupEditHealInc					= [ "You changed health increase pickup value to [#ffffff]%s." ]
	PickupEditHealWrongRange			= [ "Health value must between 1 and 100." ]
	PickupEditHealIncXNum				= [ "Health value must be in integer." ]
	PickupEditHealDec					= [ "You changed health decrease pickup value to [#ffffff]%s." ]
	PickupEditWepWithAmmo				= [ "You changed pickup weapon to [#ffffff]%s %swith [#ffffff]%s ammo." ]
	WeaponAmmoInvalidValue				= [ "Ammo value must between 1 and 9999." ]
	PickupEditObjMove					= [ "Object moving pickup has been updated." ]
	PickupEditInvalidSecond				= [ "Time value must between 1 and 10000." ]
	PickupTimeNotNum					= [ "Time must be in number." ]
	Object2NotFound						= [ "Object 2 not found." ]
	Object1NotFound						= [ "Object 1 not found." ]
	PickupEditObjNotNum					= [ "Object ID must be in number." ]
	PickupEditObjmoveSyntax				= [ "Syntax, /editpickup [ID] prop [object 1] [object 2] [time (in seconds)"]
	PickupEditWepSyntax					= [ "Syntax, /editpickup [ID] prop [weapon] [ammo]" ]
	PickupEditHealSyntax				= [ "Syntax, /editpickup [ID] prop [health value]"]
	PickupEditTypeSyntax				= [ "Syntax, /editpickup [ID] type [health increase/health decrease/weapon/objmovepos/objmoverot/cash/teleport/explosive/remove]"]
	PickupEditObjRot					= [ "Object rotation pickup has been updated." ]
	PickupEditCash						= [ "You edited picked cash to [#ffffff]$%s"]
	PickupCashValueCantMoreThan1m		= [ "Cash value cannot be more than $1,000,000." ]
	PickupCashNotEnoughCash				= [ "You dont have enough cash." ]
	PickupCashValueLessThan0			= [ "Cash value cannot less than 0." ]
	PickupCashValueLessXNum				= [ "Cash value must be in integer." ]
	PickupEditCashSyntax				= [ "Syntax, /editpickup [ID] prop [cash value] [picked value]" ]
	PickupTeleport						= [ "Teleport pickup has been updated." ]
	PickupEditTeleSyntax				= [ "Syntax, /editpickup [ID] prop [Object 1]" ]
	PickupEditDontHaveType				= [ "This pickup does not have any special features, use '/editpickup [ID] type' to select one." ]
	PickupLevel							= [ "Pickup level has been updated to [#ffffff]%s." ]
	LevelXNum							= [ "Level must be in number." ]
	PickupEditTypeRemove				= [ "You removed this pickup's special feature." ]
	PickupEditTypeRemoveSame			= [ "This pickup does not have any special feature." ]
	EditpickupLevelSyntax				= [ "Syntax, /editpickup [ID] level [level]" ]
	PickupCashPickupValueWrong			= [ "Pickup value cannot be more than the deposit value." ]
	PickupIDNotFound					= [ "Pickup not found." ]
	PickupExplosive						= [ "Explosive pickup has been updated." ]
	ExpIDNotNum							= [ "Explosive type must be in integer." ]
	PickupEditExpSyntax					= [ "Syntax, /editpickup [ID] prop [Object 1] [Explosive type]" ]

	/* scripts/Events/Pickup/PickupCollected.nut */
	PickedHealInc						= [ "Your health has increased by [#ffffff]%s%%." ]
	PickedHealDec						= [ "Your health has decreased by [#ffffff]%s%%." ]
	PickedWep							= [ "You received weapon [#ffffff]%s %swith [#ffffff]%s ammo." ]
	PickedObjNotFound					= [ "This pickup has been removed due to missing target object." ]
	PickedCash							= [ "You picked [#ffffff]$%s." ]
	PickedNoCash						= [ "This pickup has been removed due to insufficient cash." ]
	NoPermissionPick					= [ "You dont have permission to use this pickup." ]
	
	/* scripts/Commands/Vehicle.nut */
	VehEditHandlingSyntax				= [ "Syntax, /editvehhandling [acceleration/maxspeed/traction/brake/suspension] [value/reset]" ]
	VehSettingSyntax					= [ "Syntax, /vehsetting [name/lock/radio/color1/color2/flying/armour/hydraulics]" ]
	VehRadioURLSyntax					= [ "Syntax, /vehradio [URL]" ]
	VehNotOwnAny						= [ "You do not own any vehicle." ]
	VehAlreadyInVehicle					= [ "You cannot use this command while inside a vehicle." ]
	VehNotPermissionToSpawn				= [ "You dont have permission to spawn vehicle in this world." ]
	VehInfo								= [ "Model [#ffffff]%s %sLocked [#ffffff]%s %sHealth [#ffffff]%d"]
	VehInfo1							= [ "This vehicle is currently owned by [#ffffff]%s" ]
	VehNotInVehicle						= [ "You must be inside vehicle to use this command." ]
	EditHandlingReset					= [ "You resetted vehicle handling [#ffffff]%s %s." ]
	EditHandling						= [ "You edited vehicle handling [#ffffff]%s %sto [#ffffff]%f %sCost [#ffffff]%s Vice Coins" ]
	VehHandlingResetDefault 			= [ "This vehicle handling already on default value." ]
	VehNeedCointoEditHandling			= [ "You need %s Vice Coin to edit vehicle handling." ]
	VehEditHandlingNoFloat				= [ "Value must be in integer or float." ]
	VehNotOwner							= [ "You are not owner of this vehicle." ]
	VehSell								= [ "You sold vehicle [#ffffff]%s %sand you got [#ffffff]%sVice Coin." ]
	VehSettingName						= [ "You changed this vehicle name to [#ffffff]%s." ]
	VehSettingNameSyntax				= [ "Syntax, /vehsetting name [name]" ]
	VehSettingUnlock					= [ "You unlocked this vehicle." ]
	VehSettingLock						= [ "You locked this vehicle." ]
	VehSettingOffRadio					= [ "You disabled custom radio on this vehicle." ]
	VehSettingCustomRadio				= [ "You enabled custom radio on this vehicle." ]
	VehSettingPremiumColor1				= [ "You changed this vehicle Primary color. Cost [#ffffff]%s Vice Coins" ]
	VehPrimaryPermium					= [ "This is a premium color, you need %s Vice Coins to change this vehicle primary color." ]
	VehSettingColor1					= [ "You changed this vehicle Primary color." ]
	VehSettingCol1Syntax				= [ "Syntax, /vehsetting color1 [color id]" ]
	VehSettingPremiumColor2				= [ "You changed this vehicle Secondary color. Cost [#ffffff]%s Vice Coin" ]
	VehSecondaryPermium					= [ "This is premium color, you need %s Vice Coins to change this vehicle secondary color." ]
	VehSettingColor2					= [ "You changed this vehicle Primary color." ]
	VehSettingCol2Syntax				= [ "Syntax, /vehsetting color1 [color id]" ]
	VehSettingDisableFlying				= [ "You disabled vehicle flying feature." ]
	VehSettingAlreadyXFlying			= [ "This vehicle dont have flying feature." ]
	VehSettingFlyingSyntax				= [ "Syntax, /vehsetting flying reset" ]
	VehSettingAddFlying					= [ "You enabled the vehicle flying feature. Cost [#ffffff]%s Vice Coins" ]
	VehNeedCoinToAddFlying				= [ "You need %s Vice Coin to add this feature." ]
	VehSettingDisableDriveonWater		= [ "You disabled the vehicle drive on water feature." ]
	VehSettingAlreadyXDriveonWater		= [ "This vehicle doesn't have a drive on water feature." ]
	VehSettingDriveonWaterSyntax		= [ "Syntax, /vehsetting driveonwater reset" ]
	VehSettingAddDriveonWater			= [ "You enabled vehicle drive on water feature. Cost [#ffffff]%s Vice Coins" ]
	VehNeedCoinToAddDriveonWater		= [ "You need %s Vice Coin to add this feature." ]
	VehSettingModOnlyCar				= [ "This setting is only useable in a car." ]
	VehSettingRemoveArmour				= [ "You removed armour on this vehicle." ]
	VehSettingNoArmour					= [ "This vehicle does not have extra armour." ]
	VehSettingAddArmour					= [ "You added extra armour on this vehicle. Cost [#ffffff]%s Vice Coins" ]
	VehNeedCoinToAddArmour				= [ "You need %s Vice Coin to add extra armour on this vehicle." ]
	VehSettingAlreadyHasArmour			= [ "This vehicle already has extra armour." ]
	VehEject							= [ "Sucessfully ejected from vehicle." ]
	VehFixing							= [ "Your vehicle will be fixed in 5 seconds, please do not move." ]
	VehFix								= [ "Vehicle fixed."]
	FixVehFailedMove					= [ "Vehicle fix process failed because you moved." ]
	FixVehFailedNotInVeh				= [ "Vehicle fix process failed because you have exitd the vehicle." ]
	VehFixNeedCash						= [ "You need $%s to fix this vehicle." ]
	VehFlip								= [ "Sucessfully flipped this vehicle." ]
	VehRadioURLUpdate					= [ "Vehicle radio URL updated." ]
	VehDespawn							= [ "Vehicle despawned." ]
	VehCantParkInPublic					= [ "You cannot park this vehicle at public world." ]
	VehSettingAlreadyFlying 			= [ "This vehicle already have flying feature." ]
	VehSettingAlreadyXDriveonWater		= [ "This vehicle already have drive on water feature." ]
	VehSettingRemoveHydraulics			= [ "You removed vehicle Hydraulics." ]
	VehSettingNoHydraulics				= [ "This vehicle does nott have Hydraulics." ]
	VehSettingHydraulicsSyntax			= [ "Syntax, /vehsetting hydraulics reset"]
	VehSettingAddHydraulics				= [ "Vehicle Hydraulics added. Cost [#ffffff]%s Vice Coin. %sYou use use via pressing U, J, H, K or Numpad 2, 4 ,6, 8."]
	VehNeedCoinToAddHydraulics			= [ "You need %s Vice Coin to add vehicle Hydraulics." ]
	VehSettingAlreadyHasHydraulics		= [ "This vehicle already have Hydraulics." ]
	VehPark                             = [ "Sucessfully parked your vehicle." ]
	
	/* scripts/Classes/CVehicle.nut */
	BuyVehicleSucess					= [ "You have sucessfully purchased this vehicle. You can spawn it via /getveh" ]
	NotEnoughBuyVeh						= [ "You need %s Vice Coins to purchase this vehicle." ]
	VehSpawned							= [ "You spawned your vehicle [#ffffff]%s." ]
	Maximum1ActiveVeh					= [ "Only 2 active personal vehicle allowed in public world." ]
	InvalidErrorVehID					= [ "Invalid vehicle data." ]
	Maximum10ActiveVeh					= [ "Only 10 active personal vehicle allowed in public world." ]

	/* scripts/Events/PlayerEmbarking.nut */
	VehLocked							= [ "This vehicle is locked." ]
	
	/* scripts/Miscs/AttDef.nut */
	ADTimeEnd							= [ "Times up!" ]
	ADDefWon							= [ "%s%s Team %shas won the round." ]
	ADReply								= [ "Replaying base in %d seconds." ]
	ADStartRound						= [ "Round stated. Base [#ffffff]%s" ]
	ADStartRound1						= [ "Starting base [#ffffff]%s. %sCreator [#ffffff]%s %s Defender %s%s Team" ]
	ADPackSelection						= [ "Choose your pack! You can choose using /set .Type /setlist to see available weapon set." ]
	
	/* scripts/Commands/Gang.nut */
	GangCreategangSyntax				= [ "Syntax, /acreategang [founder] [tag] [name]" ]
	GangGangsettingSyntax				= [ "Syntax, /gangsetting [description/recruit/tag]" ]
	GangGangInviteSyntax				= [ "Syntax, /ganginvite [player] [rank]" ]
	GangGangKickSyntax					= [ "Syntax, /gangkick [player]" ]
	GangGangChatSyntax					= [ "Syntax, /gangchat [text]" ]
	GangGangAddRankSyntax				= [ "Syntax, /gangaddrank [level] [name]" ]
	GangGangEditRankSyntax				= [ "Syntax, /gangeditrank [del/level] [rank]" ]
	GangGangEditPermSyntax				= [ "Syntax, /gangeditpermission [editrank/addrank/setcmdlevel/invite/chat/editsetting/kick] [level]" ]
	GangCeateGang 						= [ "You are now founder of [#ffffff]%s" ]
	AGangFoundAll 						= [ "[#ffffff]%s %sis now founder of [#ffffff]%s." ]
	GangCreateTagMoreThan4				= [ "Gang tag cannot more than 4 characters." ]
	GangCreateTagLessThan1				= [ "Gang tag cannot less than 1 character." ]
	GangAlreadyExist					= [ "Given gang already exist." ]
	GangAnnDespChang					= [ "[#ffffff]%s %shas changed gang description to [#ffffff]%s" ]
	GangSetDespSyntax					= [ "Syntax, /gangsetting description [text]" ]
	GangAnnRecChang						= [ "[#ffffff]%s %shas changed gang recruit type to [#ffffff]%s." ]
	GangAnnTagChang						= [ "[#ffffff]%s %shas changed gang tag to [#ffffff]%s" ]
	GangSetTagSyntax					= [ "Syntax, /gangsetting tag [text]" ]
	GangNoPermission					= [ "You dont have permission to use this gang command." ]
	GangNotMember						= [ "You are not gang member of this gang." ]
	GangNotExist						= [ "This gang does not exist." ]
	GangNoInActiveGang					= [ "You are not in any gang." ]
	GangAnnInvite						= [ "[#ffffff]%s %shas invited [#ffffff]%s %sinto the gang." ]
	GangInvite 							= [ "[#ffffff]%s %s has invited you into gang [#ffffff]%s. %sType [#ffffff]/joingang %s %sto accept this offer." ]
	GangRankNotExist					= [ "Given gang rank does not exist." ]
	GangTargetInvAlreadyInPending		= [ "Target player already have pending invite." ]
	GangTargetSameGang					= [ "Target player already in same gang." ]
	GangAnnKick							= [ "[#ffffff]%s %shas kicked [#ffffff]%s %sfrom the gang." ]
	GangCantUseOnHighLevel				= [ "You cannot use this command on target level higher than you." ]
	TargetNotInGang						= [ "Target player not in gang." ]
	GangAnnLeave						= [ "[#ffffff]%s %shas left the gang." ]
	GangAnnChat							= [ "[#ffffff]%s [Gang]: %s" ]
	GangMembersSyntax					= [ "Syntax, /gangmembers [gang]" ]
	GangAnnAddRank						= [ "[#ffffff]%s %shas added rank [#ffffff]%s" ]
	GangLevelInvalid					= [ "Given gang level should between 1 and 100." ]
	GangLevelCantOverOwnLevel			= [ "Given rank cannot higher than your level in gang." ]
	GangRankAlreadyExist				= [ "This rank already exist." ]
	GangAnnDelRank						= [ "[#ffffff]%s %shas deleted the rank [#ffffff]%s" ]
	GangRankDelSyntax					= [ "Syntax, /gangeditrank del [rank]" ]
	GangChangeRankLevel					= [ "You changed gang rank [#ffffff]%s %slevel to [#ffffff]%d." ]
	GangRankSetLevelSyntax				= [ "Syntax, /gangeditrank [level] [rank]" ]
	GangRankSetLevelSyntax				= [ "Syntax, /gangeditrank level [new level] [rank]" ]
	GangChangePerm						= [ "You changed gang permission [#ffffff]%s %slevel to [#ffffff]%d." ]
	GangInfo							= [ "Gang [#ffffff]%s %sTag [#ffffff]%s %sFounder [#ffffff]%s %sRecruit type [#ffffff]%s %sMembers [#ffffff]%d %sRanks [#ffffff]%d" ]
	GangInfo1							= [ "Description [#ffffff]%s" ]
	GangInfo2							= [ "Kills [#ffffff]%d %sDeaths [#ffffff]%d %sRatio [#ffffff]%.2f" ]
	GangInfoSyntax						= [ "Syntax, /ganginfo [gang]" ]
	GangGangJoinSyntax					= [ "Syntax, /joingang [gang]" ]
	GangAnnJoin							= [ "[#ffffff]%s %shas joined the gang." ]
	GangAnnJoinAs 						= [ "[#ffffff]%s %shas joined the gang as [#ffffff]%s" ]
	JoinGang 							= [ "You joined the gang [#ffffff]%s. %sYou can set it as active gang with /setactivegang" ]
	GangAlreadyMember					= [ "You already are gang members of this gang." ]
	GangNotOpen							= [ "This gang is not open to join." ]
	GangNotInvite						= [ "You dont have invite from this gang." ]
	GangGangSetPlrSyntax				= [ "Syntax, /gangsetplayerrank [player] [rank]" ]
	GangAnnChangePlrRank				= [ "[#ffffff]%s %shas changed [#ffffff]%s %srank to [#ffffff]%s." ]
	GangCantSetRankOverOwn				= [ "You cannot set target rank over your rank." ]
	GangAlreadyIn 						= [ "You already in a gang. You need to leave current gang to join this gang." ]
	GangCantLeaveAsFounder 				= [ "You cannot leave this gang because you are founder." ]
	GangTargetSameRank 					= [ "Target player already have same rank." ]
	GangSettingChangeColorSyntax 		= [ "Syntax, /gangsetting color [R] [G] [B]" ]
	GangAnnColorChange 					= [ "[#ffffff]%s %shas changed gang color." ]

	/* scripts/Commands/Blip.nut */
	BlipAddSyntax						= [ "Syntax, /addblip [blip type] (NOTE: blip type 0 have extra parameter)" ]
	BlipDeleteSyntax					= [ "Syntax, /deleteblip [id]" ]
	BlipFindSyntax						= [ "Syntax, /findblip [radius]" ]
	BlipCreated							= [ "Blip added." ]
	BlipColorXNum						= [ "Blip color must be in integer." ]
	BlipSizeNotNum						= [ "Blip size must be in float." ]
	BlipCreateType0Syntax				= [ "Syntax, /addblip 0 [size] [color r] [color g] [color b]" ]
	BlipDeleted							= [ "Blip deleted." ]
	BlipIDXFind							= [ "Blip not found." ]
	BlipFind 							= [ "Blip founded within radius [#ffffff]%s" ]
	
	/* scripts/Commands/Misc.nut */
	PlayerSettingStaffSyntax			= [ "Syntax, /pset [skin/spec/team/joinmessage/showcountry/teleport/lobbyspawn/hitsound/hud]" ]
	PlayerSettingSyntax					= [ "Syntax, /pset [skin/spec/team/showcountry/teleport/hitosund/lobbyspawn/hud]" ]
	PMessageSettingSyntax				= [ "Syntax, /pset [killmessage/privatemessage/helpmessage/messagestyle]" ]
	SetActiveGangSyntax					= [ "Syntax, /setactivegang [gang]" ]
	SetSkin								= [ "Your skin has been changed." ]
	SkinIDNotNum						= [ "Skin id must be integer." ]
	SettingSkinSyntax					= [ "Syntax, /pset skin [skin id]" ]
	SetAllowSpec						= [ "Player now allowed to spectate you." ]
	SetDisallowSpec						= [ "Player now disallow to spectate you." ]
	SetTeamGang							= [ "You set your team to [#ffffff]Gang." ]
	SetTeamFree							= [ "You set your team to [#ffffff]Free." ]
	SetJoinPartMsgDisallow				= [ "Your join/part message now not loger shown." ]
	SetJoinPartMsgAllow 				= [ "Your join/part now showing." ]
	DisallowShowCountry					= [ "Your country not longer showing on join." ]
	AllowShowCountry					= [ "Your country now showing on join." ]
	DisallowKillmessage					= [ "Kill message not longer showing for you." ]
	AllowKillmessage					= [ "Kill messagw now showing." ]
	DisallowPMmessage					= [ "You disallowed incoming private message." ]
	AllowPMmessage						= [ "You allowed incoming private message." ]
	DisallowHelpMessage					= [ "Help message now not longer show for you." ]
	AllowHelpMessage					= [ "Help message now showing for you." ]
	SetActiveGang 						= [ "You set active gang to [#ffffff]%s." ]
	SameActiveGang						= [ "Given gang already as active gang." ]
	TargetNoItem						= [ "Target player does not have any item in inventory." ]
	NotPermissionViewInvent				= [ "You dont have permission to view other player inventory." ]
	NotItem								= [ "You dont have any item in inventory." ]
	GetPermTarget						= [ "[#ffffff]%s %sPermissions" ]
	GetPermTarget1						= [ "Staff [#ffffff]%s %sMapper [#ffffff]%s %sVIP [#ffffff]%s" ]
	GetPermTarget3						= [ "Your permissions" ]
	GetForum							= [ "Server forum [#ffffff]%s" ]
	GetDiscord							= [ "Server discord invite link [#ffffff]%s" ]
	OnlineMod							= [ "Online moderator [#ffffff]%s" ]
	OnlineAdmin							= [ "Online administrator  [#ffffff]%s" ]
	OnlineSrAdmin						= [ "Online senior administrator [#ffffff]%s" ]
	OnlineManager						= [ "Online manager [#ffffff]%s" ]
	OnlineOwner							= [ "Online owner [#ffffff]%s" ]
	XAdminOnline						= [ "No admin online." ]
	GetCmdSyntax						= [ "Syntax, /cmds [account/deathmatch/weapon/world/object/pickup/blip/vehicle/misc/location/gang/item/vip/anim/chat/event]" ]
	TargetFPSLimit						= [ "[#ffffff]%s %sPing [#ffffff]%s %sFPS [#ffffff]%s"]
	OwnFPSLimit							= [ "Your Ping [#ffffff]%s %sFPS [#ffffff]%s"]
	TargetCountry						= [ "[#ffffff]%s %sCountry [#ffffff]%s" ]
	TargetCountryHidden					= [ "Target player country is not visible." ]
	GetStuntKey							= [ "Key can be used in stunt world [#ffffff]G - Boost, H - Fix vehicle, B - Instant vehicle stop, N - Flip vehicle, M - Vehicle jump" ]
	GetVehicleKey						= [ "Vehicle Hydraulics [#ffffff] H or Numpad 4 - Hydraulic left, K or Numpad 6 - Hydraulic right, U or Numpad 8 - Hydraulic up, J or Numpad 2 - Hydraulic down" ]
	GetMappingKey						= [ "Mapping keys [#ffffff]Arrow keys - XY or Angle edit, Page up or down, Z or Angle Z edit or Sensitivity adjust, F2 - Change edit mode, L - Clone object, Backspace - Save object/pickup, Delete - Delete object/pickup, F3 - Hide/show hud elements" ]
	GetKeybindSyntax					= [ "Syntax, /keybinds [stunt/vehicle/mapping]" ]
	ServerInfo							= [ "Version [#ffffff]%s %sLast update [#ffffff]%s %sUptime [#ffffff]%s" ]
	ChangeTextStyle						= [ "You changed message style to [#ffffff]style %d." ]
	GetCountrySyntax					= [ "Syntax, /country [player]" ]
	SetAllowTP 							= [ "Players can now teleport to you." ]
	SetDisallowTP 						= [ "Player can no longer teleport to you." ]
	ChangewepName 						= [ "Weapon [#ffffff]%s %sname has changed to [#ffffff]%s" ]
	NoItem 								= [ "You dont have item %s." ]
	Nuked 								= [ "[#ffffff]%s %shas been nuked by [#ffffff]%s!" ]
	NukePlayer 							= [ "You sucessfully nuked [#ffffff]%s" ]
	NukePlr 							= [ "[#ffffff]%s %shas nuked you." ]
	CantNukeSelf 						= [ "You cannot nuke yourself." ]
	TargetNotSameWorld 					= [ "Target player not in this world." ]
	NukeCooldown 						= [ "You need wait %s before you can use this command." ]
	ChangeWepNameSyntax 				= [ "Syntax, /changewepname [weapon] [name]" ]
	NukePlrSyntax 						= [ "Syntax, /nuke [player]" ]
	GetModCmd 							= [ "Moderator commands [#ffffff]/kick /mute /unmute /agoto /agotoloc /agotoworld /get /settime /setweather /sethp /ann /spawnveh /setwep /setplayeroption /aduty /ac /sc /alias /getuid /getinfo /addanim /deleteanim" ]
	GetAdminCmd 						= [ "Administrator commands [#ffffff]/kick /mute /unmute /agoto /agotoloc /agotoworld /get /settime /setweather /sethp /ann /spawnveh /setwep /setplayeroption /aduty /ac /sc /alias /getuid /getinfo /addanim /deleteanim /genpass /ban /unban /rewardcash /rewardcoin /setspawnloc /setarm /alogin /setworldowner" ]
	GetSeniorCmd 						= [ "Senior Administrator commands [#ffffff]/kick /mute /unmute /agoto /agotoloc /agotoworld /get /settime /setweather /sethp /ann /spawnveh /setwep /setplayeroption /aduty /ac /sc /alias /getuid /getinfo /addanim /deleteanim /genpass /ban /unban /rewardcash /rewardcoin /setspawnloc /setarm /alogin /achangename  /setworldowner" ]
	GetManCmd 							= [ "Manager commands [#ffffff]/kick /mute /unmute /agoto /agotoloc /agotoworld /get /settime /setweather /sethp /ann /spawnveh /setwep /setplayeroption /aduty /ac /sc /alias /getuid /getinfo /addanim /deleteanim /genpass /ban /unban /rewardcash /rewardcoin /setspawnloc /setarm /alogin /achangename /setworldowner /acreategang /setpermission /setrank /setvip /hc" ]
	GetOwnerCmd 						= [ "Owner commands [#ffffff]/kick /mute /unmute /agoto /agotoloc /agotoworld /get /settime /setweather /sethp /ann /spawnveh /setwep /setplayeroption /aduty /ac /sc /alias /getuid /getinfo /addanim /deleteanim /genpass /ban /unban /rewardcash /rewardcoin /setspawnloc /setarm /alogin /achangename /setworldowner /acreategang /setpermission /setrank /setvip /exe /exec /hc /restartserver /resetpermission" ]
	GetCmdSyntaxAdmin					= [ "Syntax, /cmds [account/deathmatch/weapon/world/object/pickup/blip/vehicle/misc/location/gang/item/admin/vip/anim/chat/event]" ]
	ReportPlrSyntax						= [ "Syntax, /report [player] [reason]" ]
	ReportSend 							= [ "You reported player [#ffffff]%s %sfor %s" ]
	AReport 							= [ "[#ffffff]%s %shas reported [#ffffff]%s %sReason [#ffffff]%s" ]
	AlreadyReported 					= [ "You already reported this player." ]

	/* scripts/Events/PlayerMessage.nut */
	onChatGang							= [ "[#ffffff]%s %s%s[#ffffff]: %s" ]
	onChat 								= [ "%s%s[#ffffff]: %s" ]
	MutedCantTalk						= [ "You are muted." ]
	NotLoggedCantTalk 					= [ "You must be logged-in to be able to talk." ]

	/* scripts/Classes/CAdmin.nut */
	Kickban	 							= [ "You are currently banned by [#ffffff]%s %sReason [#ffffff]%s %sOn [#ffffff]%s" ]
	KickbanTimered1						= [ "Your ban is set to expire on [#ffffff]%s" ]
	UnbanForum							= [ "Post an unban appeal on [#ffffff]%s" ]
	MuteNotice							= [ "You are currently muted by [#ffffff]%s %sReason [#ffffff]%s %sOn [#ffffff]%s" ]
	UnmuteForum 						= [ "Post unshun appeal on [#ffffff]%s" ]
	UnmuteDuration						= [ "You mute is set to expire on [#ffffff]%s" ]
	InstanceExeeded						= [ "Your account registration limit has exeeded." ]
	ABanAll								= [ "[#ffffff]%s %s %shas been banned [#ffffff]%s Reason [#ffffff]%s" ]
	ABannedKick							= [ "You have been banned from the server. Post an unban appeal on [#ffffff]%s" ]
	ABanTimeredAll						= [ "[#ffffff]%s %s %shas banned [#ffffff]%s %sReason [#ffffff]%s %sDuration [#ffffff]%s" ]
	AMuteAll							= [ "[#ffffff]%s %s %shas muted [#ffffff]%s %sReason [#ffffff]%s" ]
	AMuteTimeredAll						= [ "[#ffffff]%s %s %shas muted [#ffffff]%s %sReason [#ffffff]%s %sDuration [#ffffff]%s" ]

	/* scripts/Commands/Admin.nut */
	AKickSyntax							= [ "Syntax, /kick [player] [reason]" ]
	ABanSyntax 							= [ "Syntax, /ban [player] [y/w/d/h/m] [reason]" ]
	AMuteSyntax							= [ "Syntax, /mute [player/all] [y/w/d/h/m] [reason]" ]
	AMuteSyntaxMod						= [ "Syntax, /mute [player] [y/w/d/h/m] [reason]" ]	
	AUnmuteSyntax						= [ "Syntax, /unmute [player/all]" ]
	AUnmuteSyntaxMod					= [ "Syntax, /unmute [player]" ]
	AGotoSyntax 						= [ "Syntax, /agoto [player]" ]
	AGotolocSyntax						= [ "Syntax, /agotoloc [location]" ]
	AGotoworldSyntax					= [ "Syntax, /gotoworld [world]" ]
	ASetpermissionSyntax				= [ "Syntax, /setpermission [player] [admin/mapper] [level]" ]
	ASetrankSyntax						= [ "Syntax, /setrank [player] [admin/mapper] [name]" ]
	AGetSyntax							= [ "Syntax, /get [player/all/allworld]" ]
	AGetSyntaxMod 						= [ "Syntax, /get [player/allworld]" ] 
	ARewardCashSyntax					= [ "Syntax, /rewardcash [player] [amount]" ]
	ARewardCoinSyntax					= [ "Syntax, /rewardcoin [player] [amount]" ]
	AExecuteSyntax						= [ "Syntax, /exe [code]" ]
	AExecuteClientSyntax				= [ "Syntax, /exec [code]" ]
	ASetTimeSyntax						= [ "Syntax, /settime [hour] [minute]" ]
	ASetWeatherSyntax					= [ "Syntax, /setweather [id]" ]
	AHealSyntax							= [ "Syntax, /sethp [player/all/allworld] [value]" ]
	AHealSyntaxMod						= [ "Syntax, /sethp [player/allworld] [value]" ]	
	AAnnSyntax							= [ "Syntax, /ann [player/all/allworld] [text]" ]
	ASpawnvehSyntax						= [ "Syntax, /spawnveh [model]" ]
	ASetWepSyntax						= [ "Syntax, /setwep [player/all/allworld] [weapon] [ammo]" ]
	ASetWepSyntaxMod					= [ "Syntax, /setwep [player/allworld] [weapon] [ammo]" ]
	ASetspawnlocSyntax					= [ "Syntax, /setspawnloc [player] [set/off/location]" ]
	AUnbanSyntax						= [ "Syntax, /unban [full name]" ]
	ASetVIPSyntax						= [ "Syntax, /setvip [player] [temp/permanent/take]" ]
	ASetPlayerOptionSyntax				= [ "Syntax, /setplayeroption [player/all/allworld] [canattack/cantattack/canmove/cantmove]" ]
	ASetPlayerOptionSyntaxMod			= [ "Syntax, /setplayeroption [player/allworld] [canattack/cantattack/canmove/cantmove]" ]	
	ASetArmSyntax						= [ "Syntax, /setarm [player/all/allworld] [value]" ]
	AKickAll							= [ "[#ffffff]%s %s %shas kicked [#ffffff]%s %sReason [#ffffff]%s" ]
	CantUseOnHighCmd					= [ "You cannot use this command on higher staff." ]
	CantUseCommandSelf					= [ "You cant use this command on yourself." ]
	AWrongTimeFormat					= [ "Wrong time format. It should be ?y/?w/?d/?h/?m." ]
	AUnbanAll							= [ "[#ffffff]%s %s %shas unbanned [#ffffff]%s" ]
	ATargetNotBanned					= [ "Target player is not banned." ]
	ATargetNotFound						= [ "Target player account not found." ]
	AMuteAll 							= [ "[#ffffff]%s %s %shas muted all players. Reason [#ffffff]%s %sDuration [#ffffff]%s" ]
	AUnmuteAll							= [ "[#ffffff]%s %s %shas unmuted all players." ]
	AUnmuteAllPlr						= [ "[#ffffff]%s %s %shas unmuted [#ffffff]%s" ]
	ATargetNotMuted						= [ "Target player is not muted." ]
	StaffGotoPlr						= [ "[#ffffff]%s %s %shas teleport to [#ffffff]%s" ]
	StaffGotoWorld						= [ "[#ffffff]%s %s %shas switched to world [#ffffff]%s" ]
	StaffSetAdminLevel					= [ "[#ffffff]%s %s %shas set [#ffffff]%s %sadmin permission to [#ffffff]%s" ]
	StaffLevelInvalid					= [ "Admin level must between 0 and 5." ]
	StaffSetRank						= [ "[#ffffff]%s %s %shas set [#ffffff]%s %sadmin rank to [#ffffff]%s" ]
	StaffGetPlr							= [ "[#ffffff]%s %s %sis getting [#ffffff]%s" ]
	AGotoloc 							= [ "[#ffffff]%s %s %shas gotoloc [#ffffff]%s" ]
	AAddCashAll							= [ "[#ffffff]%s %s %shas rewarded [#ffffff]%s [#ffffff]$%s." ]
	AAddCoinAll							= [ "[#ffffff]%s %s %shas rewarded [#ffffff]%s [#ffffff]%s Vice Coin." ]
	AExec 								= [ "Code [#ffffff]%s %shas sucessfully executed." ]
	AExecError 							= [ "Execute error [#ffffff]%s" ]
	ASetTimeAll							= [ "[#ffffff]%s %s %shas changed server time to [#ffffff]%d:%d" ]
	InvalidMinute						= [ "Minute should between 0 and 60." ]
	InvalidHour 						= [ "Hour should between 0 and 23." ]
	ASetWeatherAll						= [ "[#ffffff]%s %s %shas changed server weather to [#ffffff]%d" ]
	AHealAll							= [ "[#ffffff]%s %s %shas set all player hp to [#ffffff]%d." ]
	AHealWorldAll						= [ "[#ffffff]%s %s %shas set all player hp in world [#ffffff]%d %sto [#ffffff]%d." ]
	AHealWorldAll1 						= [ "[#ffffff]%s %s %shas set all player hp in this world to [#ffffff]%d." ]
	SetHP 								= [ "[#ffffff]%s %s %shas changed your hp to [#ffffff]%d" ]
	SetHealPlrStaff						= [ "[#ffffff]%s %s %shas set [#ffffff]%s %sto [#ffffff]%d." ]
	AAnnAll								= [ "[#ffffff]%s %s %shas sending announcement [#ffffff]%s %sto all players." ]
	AAnnWorld							= [ "[#ffffff]%s %s %shas sending announcement [#ffffff]%s %sto world [#ffffff]%d" ]
	AAnnPlr 							= [ "[#ffffff]%s %s %shas sending announcement [#ffffff]%s %sto [#ffffff]%s" ]
	ASpawnVeh 							= [ "[#ffffff]%s %s %shas spawned vehicle [#ffffff]%s" ]
	InvalidVehModel 					= [ "Invalid vehicle model." ]
	AGiveWepAll 						= [ "[#ffffff]%s %s %shas given weapon [#ffffff]%s %swith [#ffffff]%d ammo %sto all players." ]
	AGiveWepWorld						= [ "[#ffffff]%s %s %shas given weapon [#ffffff]%s %swith [#ffffff]%d ammo %sto world [#ffffff]%d" ]
	AGiveWepWorld1						= [ "[#ffffff]%s %s %shas given weapon [#ffffff]%s %swith [#ffffff]%d ammo %sto this world." ]
	AGiveWepPlr							= [ "[#ffffff]%s %s %shas given weapon [#ffffff]%s %swith [#ffffff]%d ammo %sto [#ffffff]%s" ]
	SetWepPlrWorld 						= [ "[#ffffff]%s %s %shas given you weapon [#ffffff]%s %swith [#ffffff]%d ammo"]
	ASpawnlocOnPlr 						= [ "[#ffffff]%s %s %shas changed [#ffffff]%s %sspawn location." ]
	SpawnlocLocAdminOn 					= [ "[#ffffff]%s %s %shas changed your spawn location." ]
	SpawnlocLocAdminOff 				= [ "[#ffffff]%s %s %shas disabled [#ffffff]%s %sspawn location." ]
	ASpawnlocOffPlr					 	= [ "[#ffffff]%s %s %shas disabled your spawn location." ]
	TargetSpawnlocAlreadyOff			= [ "Target player spawn location already off." ]
	SpawnlocLocAdmin 					= [ "[#ffffff]%s %s %shas changed your spawn location to location [#ffffff]%s" ]
	ASpawnlocLocPlr						= [ "[#ffffff]%s %s %shas changed [#ffffff]%s %sspawn location to [#ffffff]%s" ]
	ASetVIPPlr							= [ "[#ffffff]%s %s %shas changed [#ffffff]%s %sVIP status to [#ffffff]%s" ]
	SetVIPTarget						= [ "[#ffffff]%s %s %shas changed your VIP status to [#ffffff]%s" ]
	ASetVIPPlr							= [ "[#ffffff]%s %s %shas changed [#ffffff]%s %sVIP status to [#ffffff]%s" ]
	SetVIPTarget1 						= [ "Your VIP status will lasts for [#ffffff]%s." ]
	SetVIPTargetOff 					= [ "[#ffffff]%s %s %shas revoke your VIP status." ]
	ATakeVIPPlr 						= [ "[#ffffff]%s %s %shas revoked [#ffffff]%s %sVIP status." ]
	ACanAttackAll 						= [ "[#ffffff]%s %s %shas enable all players attack ability." ]
	ACantAttackAll						= [ "[#ffffff]%s %s %shas disable all players attack ability." ]
	ACanMoveAll							= [ "[#ffffff]%s %s %shas unfroze all players." ]
	ACantMoveAll						= [ "[#ffffff]%s %s %shas freeze all players." ]
	PlrOptionAllSyntax 					= [ "Syntax, /setplayeroption all [canattack/cantattack/canmove/cantmove]" ]
	ACanAttackWorld 					= [ "[#ffffff]%s %s %shas enable all players attack ability in this world." ]
	ACanAttackWorld1					= [ "[#ffffff]%s %s %shas enable all players attack ability in world [#ffffff]%d." ]
	ACantAttackWorld 					= [ "[#ffffff]%s %s %shas disabled all players attack ability in this world." ]
	ACantAttackWorld1					= [ "[#ffffff]%s %s %shas disabled all players attack ability in world [#ffffff]%d." ]
	ACanMoveWorld 						= [ "[#ffffff]%s %s %shas unfroze all players attack ability in this world." ]
	ACanMoveWorld1						= [ "[#ffffff]%s %s %shas unfroze all players attack ability in world [#ffffff]%d." ]
	ACantMoveWorld 						= [ "[#ffffff]%s %s %shas freeze all players attack ability in this world." ]
	ACantMoveWorld1						= [ "[#ffffff]%s %s %shas freeze all players attack ability in world [#ffffff]%d." ]
	PlrOptionWorldSyntax				= [ "Syntax, /setplayeroption allworld [canattack/cantattack/canmove/cantmove]" ]
	CanAttackTarget 					= [ "[#ffffff]%s %s %shas enable your attack ability." ]
	ACanAttackPlr 						= [ "[#ffffff]%s %s %shas enable [#ffffff]%s %sattack ability." ]
	CantAttackTarget 					= [ "[#ffffff]%s %s %shas disabled your attack ability." ]
	ACantAttackPlr 						= [ "[#ffffff]%s %s %shas disabled [#ffffff]%s %sattack ability." ]
	CanMoveTarget 						= [ "[#ffffff]%s %s %shas unfroze you." ]
	ACanMovePlr 						= [ "[#ffffff]%s %s %shas unfroze [#ffffff]%s" ]
	CantMoveTarget 						= [ "[#ffffff]%s %s %shas freeze your attack ability." ]
	ACantMovePlr 						= [ "[#ffffff]%s %s %shas freeze [#ffffff]%s" ]
	PlrOptionTargetSyntax				= [ "Syntax, /setplayeroption [player] [canattack/cantattack/canmove/cantmove]" ]
	AArmAll 							= [ "[#ffffff]%s %s %shas set all player armour value to [#ffffff]%d." ]
	AArmWorldAll 						= [ "[#ffffff]%s %s %shas set all player in this world armour value to [#ffffff]%d." ]
	SetArmStaff							= [ "[#ffffff]%s %s %shas set all players armour value to [#ffffff]%d %sin world [#ffffff]%d." ]
	SetArm 								= [ "[#ffffff]%s %s %shas changed your armour value to [#ffffff]%d." ]
	SetArmPlrStaff 						= [ "[#ffffff]%s %s %shas changed [#ffffff]%s %sarmour value to [#ffffff]%d." ]
	AAdminDutyOff 						= [ "[#ffffff]%s %s %snot longer on admin duty." ]
	AAdminDutyOn						= [ "[#ffffff]%s %s %sis now on admin duty." ]
	NoPermissionUseCmd 					= [ "You dont have permission to use this command." ]
	ASpecAll							= [ "[#ffffff]%s %s %shas spectating [#ffffff]%s." ]
	SpecPlayer 							= [ "You are now spectating [#ffffff]%s %sType /exitspec to exit spectate mode." ]
	TargetDisallowSpec 					= [ "Target player disabled spectate." ]
	NotSpecAnyTarget 					= [ "You are not spectating any player." ]
	ExitSpec 							= [ "You exited spectate mode." ]
	GetUIDTitle 						= [ "UID1 and UID2 of [#ffffff]%s" ]
	GetUID1 							= [ "[#ffffff]%s %sUID1" ]
	GetUID2 							= [ "[#ffffff]%s %sUID2"]
	TargetAccNotExist 					= [ "Given name does not exist in database." ]
	GetInfoTitle 						= [ "Player info of [#ffffff]%s %sAccount ID [#ffffff]%d" ]
	GetInfo1 							= [ "IP [#ffffff]%s %sCountry [#ffffff]%s" ]
	GetInfo2 							= [ "Away [#ffffff]%s %sWorld [#ffffff]%d" ]
	GetInfo3 							= [ "Cash [#ffffff]$%s %sCoin [#ffffff]%s" ]
	AGetInfoSyntax 						= [ "Syntax, /getinfo [player/account name]" ]
	AGetUIDSyntax						= [ "Syntax, /getuid [player/account name]" ]
	NotOnLobbySpec 						= [ "You must be in the lobby to spectate player." ]
	StaffSetAdminMapperLevel			= [ "[#ffffff]%s %s %shas set [#ffffff]%s %sadmin permission to [#ffffff]%s" ]
	MapperLevelInvalid					= [ "Mapper level must be between 0 and 1." ]
	AAdminChatSyntax 					= [ "Syntax, /ac [text]" ]
	AMapperChatSyntax 					= [ "Syntax, /mc [text]" ]
	AVIPChatSyntax 						= [ "Syntax, /vipchat [text]" ]
	AStaffChatSyntax 					= [ "Syntax, /sc [text]" ]
	ChangePermissionAdminTarget 		= [ "[#ffffff]%s %s %shas set your admin permission to [#ffffff]%s." ]
	StaffSetMapperLevel					= [ "[#ffffff]%s %s %shas set [#ffffff]%s %smapper permission to [#ffffff]%s" ]
	ChangePermissionMapperTarget		= [ "[#ffffff]%s %s %shas set your mapper permission to [#ffffff]%s." ]
	ChangeRankTarget 					= [ "[#ffffff]%s %s %shas changed your admin rank to [#ffffff]%s." ]
	ATransferAll 						= [ "[#ffffff]%s %s %shas transfered [#ffffff]%s %saccount to [#ffffff]%s" ]
	TransferTarget 						= [ "[#ffffff]%s %s %shas changed your name to [#ffffff]%s" ]
	NewAccountExist 					= [ "New account already exists." ]
	OldAccountNotExist 					= [ "Old account does not exist." ]
	AAdminChat 							= [ "[#ffffff]%s %s: %s" ]
	AResetPassSyntax 					= [ "Syntax, /genpass [player]" ]
	GenerateRandomPassScs 				= [ "Sending random generated password to [#ffffff]%s" ]
	GenerateRandomPass 					= [ "Your new password is [#ffffff]%s" ]
	TargetAlreadyLogged 				= [ "Target player already logged." ]
	AAliasSyntax 						= [ "Syntax, /alias [player] [uid1/uid2]" ]
	ASetVIPTimeredSyntax 				= [ "Syntax, /setvip [player] [temp] [y/w/d/h/m]" ]
	StaffSetRankMapper 					= [ "[#ffffff]%s %s %shas set [#ffffff]%s %smapper rank to [#ffffff]%s" ]
	ChangeMapperRankTarget				= [ "[#ffffff]%s %s %shas changed your mapper rank to [#ffffff]%s." ]

	/* scripts/Events/PlayerPrivateMessage.nut */
	PMTarget 							= [ "PM from [#ffffff]%s: %s" ]
	PMBlocked 							= [ "Target player disabled incoming private message." ]
	TargetOnDutyCantPM 					= [ "Target player currently in admin duty." ]
	MutedCantPM 						= [ "You cannot send private message to someone because you are muted." ]
	NotLoggedCantPM 					= [ "You must be logged to able to private message someone." ]	

	/* scripts/Events/Player/PlayerDestroyed.nut */
	PlayerTimeredOut 					= [ "[#ffffff]%s %shas lost connect with the server." ]
	PlayerKickedOut 					= [ "[#ffffff]%s %shas been kicked from the server." ]
	PlayerGameCrashed 					= [ "[#ffffff]%s %sgame crashed." ]
	PlayerPart 							= [ "[#ffffff]%s %shas left the server." ]

	/* scripts/Events/Player/ClientScriptData.nut */
	BroughtNameTag 						= [ "You purchased a weapon name tag." ]
	XCoinBuyNameTag 					= [ "You need 500 Vice Coins to purchase weapon name tag." ]
	BroughtNArmCase 					= [ "You purchased an armour case." ]
	XCoinBuyArmCase 					= [ "You need 20 Vice Coins to purchase armour case." ]
	BroughtNVehNameTag 					= [ "You purchased a vehicle name tag." ]
	XCoinBuyVehNameTag 					= [ "You need 2,500 Vice Coins to purchase vehicle name tag." ]

	/* scripts/Events/Checkpoint/CheckpointEntered.nut */
	NotOwnWarehouse						= [ "You don't own this warehouse." ]
	VehCargoSaved 						= [ "Vehicle [#ffffff]%s %shas been saved into your vehicle warehouse." ]

	/* scripts/Events/Checkpoint/VehicleExplode.nut */
	VehCargoExplode 					= [ "[#ffffff]%s %svehicle cargo exploded." ]
	VehCargoFailSelf 					= [ "You failed to deliver the vehicle cargo." ]

	/* scripts/Classes/CVehicleWarehouse.nut */
	VehCargoSelf 						= [ "Deliver this vehicle to your vehicle warehouse." ]
	VehCargoWarning 					= [ "Warning, your vehicle cargo is now visible to all players in server." ]
	VehCargoStart 						= [ "[#ffffff]%s %sis delivering the vehicle cargo." ]
	VehCargoGotoPoint 					= [ "Steal the vehicle cargo." ]

	/* scripts/Commands/VehicleCargo.nut */
	VehCargoNoCargo						= [ "You dont have any vehicle cargo to export." ]
	VehCargoExportCooldown 				= [ "You need to wait %s before you can export another vehicle cargo." ]
	VehCargoNotInWarehouse 				= [ "You must be in vehicle warehouse to use this command." ]
	VehCargoImportCooldown				= [ "You need to wait %s before you can launch another import mission." ]
	VehCargoStolen 						= [ "Your vehicle cargo has been stolen." ]


	/* Added as 5.0 */
	NoOwnWorld 							= [ "You dont own any world." ]
	WorldValueNotNum 					= [ "Value must be in integer." ]
 	ASpecSyntax 						= [ "Syntax, /spec [player]" ]
 	ErrorReport 						= [ "An error occured [#ffffff]%s %sorigin [#ffffff]%s %sline [#ffffff]%s %sfunction [#ffffff]%s" ]
 	InvalidVehID 						= [ "Invalid vehicle data. Please contract developer." ]
 	InvalidLangChange 					= [ "Your language has been changed to English due to internal error." ]
 	EditSens1							= [ "You changed edit sens to [#ffffff]%f." ]
 	OwnCountry 							= [ "Your country [#ffffff]%s" ]
 	MutedCantUseCmd 					= [ "You cant use this command because you are muted." ]
 	StaffGetPlrAll						= [ "[#ffffff]%s %s %sis getting all players." ]
 	StaffGetPlrAllWorld					= [ "[#ffffff]%s %s %sis getting all players in this world." ]
 	StaffGetPlrAllWorld1				= [ "[#ffffff]%s %s %sis getting all players in world [#ffffff]%d." ]
 	AWrongAnnType 						= [ "Announcement type should between 0 and 8." ]
 	ANoAliasFound 						= [ "No alias found." ]
 	StaffLevelInvalid 					= [ "Given level cannot over your own level." ]
 	TargetAlreadyPermVIP 				= [ "Target player already have permanent VIP." ]
 	TargetNotVIP 						= [ "Target player does not have any VIP access." ]
 	EditsensSyntax 						= [ "Syntax, /editsens [value]" ]
 	ChangeNameSyntax 					= [ "Syntax, /changename [new name]" ]
 	ChangeNameNew 						= [ "Your account name has been changed to [#ffffff]%s" ]
 	InvalidChar 						= [ "Invalid character detected." ]
 	PlayerRename 						= [ "[#ffffff]%s %sis now known as [#ffffff]%s" ]
 	ChangenameNewAlreadyUsed 			= [ "New name already used." ]
 	ChangenameNewAlreadySame    		= [ "You have that same name." ]
 	ChangenameNewTooMany 				= [ "Name length cannot more than 26." ]
 	PlayerTriedToTele 					= [ "[#ffffff]%s %swill teleport to you in 3 seconds. Dont like player teleport to you? You can disable it with /pset teleport" ]
 	HelpMessages 						= [ 
 											"You can purchase vehicle anywhere with /buyveh" 
 											"You can view your current session stats with /currentstats" 
 											"You can purchase unowned world with /buyworld" 
 											"Some glitch such as rocket glitch, ghost city glitch are allowed in private world."
 											"Join our discord server (/discord) for more update." 
 											"Tried player spectate you? You can toggle with /pset spectate" 
 											"You can change your skin with /pset skin" 
 											"World id from 4000 to 10000 now available to purchase." 
 											"You can wear armour with /equiparmour." 
 											"You can change your weapon name with /changewepname." 
 											"Type /hostevent to host an event."
 											"You can change your vehicle name with /vehsetting" 
 											"Type /gettop to check top players."
 											"You change hud style with /pset hud"
 											"Need to create own gang? You can use /creategang"
 											"You can attach text on your character with /settitle"
 											"Press F3 to show/hide hud."
 											"You can ban player from world with /worldban" 
 											"Minigun now can be used freely in private world." 
 											"You can use /doanim to use available animation."
 											"You can return to class selection after died by pressing F4."
 											"Looking for gang? You can view available gang list by /ganglist. To join gang you can use /gangjoin"
 											"You can use /dosound to play available sound."
 											"Type /keybinds mapping to view available mapping keybinds"
 											"Help message too annoying? You can disable by toggle /mset helpmessage",
 											"Admin application are now opened. Apply on forum. (/forum)"
 											"You can buy Vice Coin in lobby with /buycoin"
											"Missed update? use /updatelog to view update log."
 										]
 	AUnmuteTimered 						= [ "Auto unmuted [#ffffff]%s" ]
 	ReplaceWepSyntax 					= [ "Syntax, /replacewep [100-108]" ]
 	WeaponReplaced 						= [ "Weapon [#ffffff]%s %snow replace with [#ffffff]%s" ]
 	ChangeNameNewNotice 				= [ "You can type again to disable replacement." ]
 	ChangeNameNewNotice1 				= [ "You can type again to enable replacement." ]
 	GetMagicstick						= [ "You received [#ffffff]Magic Stick." ]
 	ASilentJoin 						= [ "[#ffffff]%s %shas silent joined from [#ffffff]%s" ]
	WorldInvalidWorld2					= [ "World id should be integer(1000-4000/5000-10000)" ]
	RewardPerHour 						= [ "Thanks for playing! You got [#ffffff]$%s %sand [#ffffff]%s XP %sas reward." ]
	InactiveMove 						= [ "You has been moved to lobby due to inactive." ]
	PickupLevelPublicWorldSyntax 		= [ "Syntax, /editpickup [ID] level [level (0-All/1-Admim/2-Mapper/3-Admin&VIP&Mapper/4-Admin&Mapper)]" ]
	SetLobbySpawn 						= [ "You changed your default lobby spawn to [#ffffff]%s" ]
	GetVIPCmd 							= [ "VIP commands [#ffffff]/vipchat /addanim" ]
	GetAnimCmd 							= [ "Anim commands [#ffffff]/doanim /animlist" ]
	AnimDoesNotExist 					= [ "Given animation does not exist. Use /animlist to view available anims." ]
	AddAnimAll 							= [ "[#ffffff]%s %s %sadded animation [#ffffff]%s" ]
	AddAnimSelf 						= [ "You added animation [#ffffff]%s" ]
	AnimExist 							= [ "Given animation already exist." ]
	StaffDeleteAnim 					= [ "[#ffffff]%s %s %sdeleted animation [#ffffff]%s" ]
	AnimXFind 							= [ "No animation found." ]
	DoAnimSyntax 						= [ "Syntax, /doanim [name]" ]
	AddAnimSyntax 						= [ "Syntax, /addanim [name] [group] [anim]" ]
	DelAnimSyntax 						= [ "Syntax, /deleteanim [name]" ]
	SoundDoesNotExist 					= [ "Given sound does not exist. Use /soundlist to view available sounds." ]
	DoSoundSyntax 						= [ "Syntax, /dosound [name]" ]
	AddSoundAll 						= [ "[#ffffff]%s %s %sadded sound [#ffffff]%s" ]
	AddSoundSelf 						= [ "You added sound [#ffffff]%s" ]
	SoundExist 							= [ "Given sound already exist." ]
	AddSoundSyntax 						= [ "Syntax, /addsound [name] [sound]" ]
	StaffDeleteSound 					= [ "[#ffffff]%s %s %sdeleted sound [#ffffff]%s" ]
	SoundXFind 							= [ "No sound found." ]
	DMArenaChangeArea 					= [ "Changing Deathmatch Arena in [#ffffff]%d seconds." ]
	DMArenaStartArea 					= [ "Starting Deathmatch Area. Location [#ffffff]%s" ]
	GotoworldAllDM 						= [ "[#ffffff]%s %shas switched to Death match world." ]
	GotoWorldSucessDM 					= [ "Sucessfully switched to death match world." ]
	MessageLocal 						= [ "[#ffffff]%s [Local]: %s" ]
	MessageLocalSyntax 					= [ "Syntax, /l [text]" ]
	MessageShout 						= [ "[#ffffff]%s [Shout]: %s!!!" ]
	MessageShoutSyntax 					= [ "Syntax, /s [text]" ]
	MessageME 							= [ "[#ffffff]%s %s" ]
	MessageMESyntax 					= [ "Syntax, /me [text]" ]
	GetChatCmd 							= [ "Chat mode [#ffffff]/l, /s, /lw, /me" ]
	LocalWhiper1 						= [ "[#ffffff]%s %shas whiper something to [#ffffff]%s" ]
	LocalWhiperRec 						= [ "[#ffffff]%s [Whiper to you]: %s" ]
	LocalWhiperSender 					= [ "[#ffffff]%s [Whiper to %s]: %s" ]
	TargetNotNear 						= [ "Target player not nearby." ]
	LocalWhiperSyntax 					= [ "Syntax, /lw [player] [text]" ]
	GotoWorldSucessDM2 					= [ "You entered Deathmatch world. Use /gotoworld or /lobby to leave this world." ]
	CantPurchaseVehError 				= [ "Could not get vehicle info. Please contract developer." ]
	ReadPM 								= [ "[#ffffff]%s %ssending private message [#ffffff]%s %sto [#ffffff]%s" ]
	VehSettingArmourSyntax 				= [ "Syntax, /vehsetting armour reset" ]
	SkinIDRange 						= [ "Skin ID range must between 0 and 230." ]
	ChangeNameNew1 						= [ "[#ffffff]%s %s %shas changed your name to [#ffffff]" ]
	AAChangeNameSyntax 					= [ "Syntax, /achangename [player] [new name]" ]
	VehSettingAlreadyDriveonWater 		= [ "This vehicle already have drive on water feature." ]
	GetPlayerModule 					= [ "[#ffffff]%s %sModule [#ffffff]%s" ]
	AReportAll 							= [ "[#ffffff]%s %shas reported [#ffffff]%s %sfor [#ffffff]%s. %sVictim world [#ffffff]%d" ]
	VehFixAnotherHealInProcess 			= [ "" ]
	DontRepeat 							= [ "Do not repeat your message." ]
	ChatCooldown 						= [ "Please wait before sending another message." ]
	SetGangTP 							= [ "Only gang members can teleport to you." ]
	GotoworldAllGridingWorld 			= [ "[#ffffff]%s %shas switched to Grinding world." ]
	GangNoPermissionChat 				= [ "You dont have permission to gang chat." ]

	JobRobSucess 						= [ "Robbery sucess! You got [#ffffff]$%s." ]
	JobRobFailedMove 					= [ "Robbery failed because you move." ]
	JobRobFailedSomeoneRobbing 			= [ "Someone is robbing this place." ]
	JobRobFailedRobbed 					= [ "Someone already robbed this place. Please try again later!" ]
	EnterGrindingWorld 					= [ "Welcome to grinding world! Here you can earn extra cash by doing job or rob the store. Death match is disallow on this world." ]
	RobPointAdded 						= [ "You added robbing point." ]
	JobRobStarting 						= [ "Robbery in process, please do not move." ]
	JobRobFailedOnJob 					= [ "You cannot rob the store while on job." ]
	JobRobFailedInVehicle 				= [ "You need to exit vehicle to rob store." ]
	
	DeliverNext 						= [ "Deliver the pizza to next checkpoint or go to nearest pizzateria to get your paycheck." ]
	NoStockLeft 						= [ "You dont have pizza left! Go to nearest pizzateria to restock or get your paycheck with /pizzpaycheck" ]
	StartAsPizzaBoy 					= [ "You are now pizza boy, enter any Pizza Boy and go to pickup point at pizzateria to start deliver." ]
	EndPizzaBoy 						= [ "You not longer pizza boy." ]
	RestockPizza 						= [ "You restocked pizza." ]
	NotInPizzaBoi 						= [ "You must be in Pizza Boy to deliver." ]
	NotInPizzaBoi2 						= [ "You must be in Pizza Boy to restock." ]
	NotPizzaBoi3 						= [ "You must be Pizza Boy to take deliver." ]
	DeliverScs 							= [ "Deliver sucess." ]
	NoNeedStockPizza 					= [ "You no need to restock pizza!" ]
	LosePizza 							= [ "You lose all pizza." ]
	StartPizzaJob2 						= [ "Go to nearest pizzateria to start pizza delivery." ]
	CantEnterPickupInVehicle 			= [ "You cannot pick this pickup while in vehicle." ]
	NotNearPizza 						= [ "You need to be at pizzateria to use this command." ]
	PizzaPayCheck 						= [ "You got [#ffffff]$%s %sfor delivery pay check." ]
	NoPizzaIncome 						= [ "Deliver some pizza to collect pay paycheck!" ]

	AAddCashAll2						= [ "[#ffffff]%s %s %shas rewarded all players with [#ffffff]$%s." ]
	gangviewrankSyntax 					= [ "Syntax, /gangviewrank [gang name]"]
	GiveWorldSyntax 					= [ "Syntax, /giveworld [player]" ]
	GiveWorld 							= [ "You given this world ownership to [#ffffff]%s" ]
	GiveWorld2 							= [ "[#ffffff]%s %shas given world ownership of [#ffffff]%d %sto you." ]
	NotPermissionViewWorld 				= [ "You dont have permission to view other player world." ]
	AlreadyCD 							= [ "An countdown already in process." ]
	ObjEditingWithModel 				= [ "You are now edit this object. Model [#ffffff]%d %sID [#ffffff]%d" ]
	ObjGetModel 						= [ "Object model id [#ffffff]%d" ]
	SettingHitsoundSyntax 				= [ "Syntax, /psetting hitsound [off/sound id]" ]
	HitSoundOn 							= [ "You changed hit sound." ]
	SoundNotNum 						= [ "Sound ID must be in integer." ]
	HitSoundOff							= [ "You turn off hit sound." ]
	TargetGetLoc 						= [ "[#ffffff]%s %sWorld [#ffffff]%s" ]
	GetLoc 								= [ "Your world [#ffffff]%s" ]
	GetHPArm 							= [ "Your HP [#ffffff]%d %sArmour [#ffffff]%d" ]
	GetHPArm2							= [ "[#ffffff]%s %sHP [#ffffff]%d %sArmour [#ffffff]%d" ]
	AAdminChat2 						= [ "[#ffffff]%s %s [Staff chat]: %s" ]
	AAdminChat3 						= [ "[#ffffff]%s %s [Admin chat]: %s" ]
	AAdminChat4							= [ "[#ffffff]%s %s [Mapper chat]: %s" ]
	AAdminChat5							= [ "[#ffffff]%s %s [VIP chat]: %s" ]
	AAdminChat6							= [ "[#ffffff]%s %s [Managament chat]: %s" ]
	GetSpree 							= [ "Player on killing streak [#ffffff]%s" ]
	XOnSpree 							= [ "No one is on killing streak." ]
	onDiscordChat 						= [ "%s%s [Discord]: %s" ]
	AHCSyntax 							= [ "Syntax, /hc [text]" ]

	PickupCreateError 					= [ "An error occurred while adding pickup. [#ffffff]%s" ]
	ObjectCreateError					= [ "An error occurred while adding object. [#ffffff]%s" ]
	CreateVehicleError 					= [ "An error occurred while spawning vehicle. [#ffffff]%s" ]
	CloneObjectError 					= [ "An error occurred while cloning object. [#ffffff]%s" ]
	SpawnObjectError 					= [ "An error occurred while spawning object. [#ffffff]%s" ]
	SpawnPickupError 					= [ "An error occurred while spawning pickup. [#ffffff]%s" ]
	SpawnVehicleError 					= [ "An error occurred while spawning vehicle. [#ffffff]%s" ]
	CreateMarkerError 					= [ "An error occurred while creating blip. [#ffffff]%s" ]
	PickPickupError 					= [ "An error occurred while picking pickup. [#ffffff]%s" ]

	AdminLoginSyntax 					= [ "Syntax, /alogin [account] [password]" ]
	ALogin 								= [ "[#ffffff]%s %s %slogged as admin account [#ffffff]%s" ]
	ATargetNotAdmin 					= [ "Target account is not admin." ]
	ATargetOnline 						= [ "Target player is online." ]
	LogoutAll 							= [ "[#ffffff]%s %shas logged out." ]
	Logout 								= [ "You has logged out." ]
	HitReport 							= [ "[#ffffff]%s %swas hitted by [#ffffff]%s %sless than 5 seconds ago." ]
	UclaimCrate 						= [ "You have unclaim free crate, use /claimcrate to claim your crate." ]
	ModExpired 							= [ "Your admin pass has expired." ]
	UseSyntax 							= [ "Syntax, /use [vippass/nukepass/weapontag/vehiclenametag/worldpass/adminpass/leveluppass]" ]
	UsedVIPPass 						= [ "You used an VIP Pass. Use /rank to check VIP duration." ]
	CantUseVIPPass 						= [ "You cannot use VIP Pass." ]
	UseCmdInstead 						= [ "Please use command [#ffffff]%s %sinstead." ]
	UsedWorldPass						= [ "World Pass activated. No coin will deduce on your next world purchase." ]
	UsedAdminPass 						= [ "You used an Admin Pass." ]
	AdminPassExpiredDate 				= [ "Your temporary Moderator lasts for [#ffffff]%s." ]
	CantUseAdminPass					= [ "You cannot use Admin Pass." ]
	UsedHiddenPass 						= [ "You used hidden pass. It will lasts for 1 session." ]
	EquipSantaHat 						= [ "You equipped Santa Hat." ]
	UnlockCrateAll 						= [ "[#ffffff]%s %sopened an crate and found %s." ]
	UnlockCrate 						= [ "You unlocked the crate and found %s." ]
	RecCrate 							= [ "You received 2x crate as login reward. Unlock it with /unlockcrate." ]
	RecCrate2 							= [ "You received another crate." ]
	WaitClaim 							= [ "You need to wait %s to claim your crate again." ]
	InviteSyntax 						= [ "Syntax, /invite [player]" ]
	AskTargetToJoinWorld 				= [ "You sended request to [#ffffff]%s %sfor join this world." ]
	RequestJoinWorld 					= [ "[#ffffff]%s %shas send you request to join world [#ffffff]%s %s.Type /accept to accept invite." ]
	TargetHasPendingInvite 				= [ "Target player has pending request." ]
	TargetOnSameWorld 					= [ "Target player already on this world." ]
	AcceptJoinWorldRequest 				= [ "You accepted the world invite." ]
	NotInvitePending 					= [ "You dont have any pending request." ]
	RejectJoinWorldRequest 				= [ "You rejected the request." ]
	AUnbanAll 							= [ "[#ffffff]%s %s %sunbanned [#ffffff]%s" ]
	APlrNotBanned 						= [ "This player is not banned." ]
	ErrorShown 							= [ "An error occured, please contract owner." ]
	UnbanSyntax 						= [ "Syntax, /unban [player]" ]
	GiveWorld3							= [ "[#ffffff]%s %s %shas given world ownership of [#ffffff]%d %sto you." ]
	SetWorldOwnerAll 					= [ "[#ffffff]%s %s %schanged world [#ffffff]%d %sownership to [#ffffff]%s" ]
	SetworldOwnerSyntax 				= [ "Syntax, /setworldowner [player]" ]
	ResetPermSyntax 					= [ "Syntax, /resetpermission [player/full name]" ]
	ResetPermAll 						= [ "[#ffffff]%s %s %sresetted [#ffffff]%s %spermissions." ]
	ResetPermPM 						= [ "[#ffffff]%s %s %shas resetted your permissions." ]
	InvalidItem 						= [ "Invalid item. It should be [#ffffff]armourcase/crate/vippass/adminpass/worldpass/nukepass/hiddenpass/weapontag/vehiclenametag/gangpass/leveluppass" ]
	SendTradeOffer 						= [ "Sending trade offer to [#ffffff]%s. %sOffer will expired after 30 seconds." ]
	SendTradeOffer2 					= [ "[#ffffff]%s %swant to trade %s [#ffffff][%d] %sfor your %s [#ffffff][%d]" ]
	SendTradeOffer3 					= [ "Type [#ffffff]/tradeaccept %sto accept. [#ffffff]/tradedeny %sto reject offer." ]
	SendTradeOfferTimeout 				= [ "Awaiting offer to [#ffffff]%s %shas timeout." ]
	SendTradeOfferTimeout2 				= [ "Awaiting offer from [#ffffff]%s %shas timeout." ]
	TargetHasPendingTradeInvite 		= [ "Target player already have trade offer pending." ]
	TradePendingWaiting 				= [ "You already have pending offer." ]
	TradeScsAll 						= [ "[#ffffff]%s %shave received %s [#ffffff][%d] %sin trade." ]
	TradeSucs 							= [ "Trade sucess." ]
	TradeCancelDonthaveItem3 			= [ "Trade cancelled because you dont have item %s." ]
	TradeCancelDonthaveItem4    		= [ "Trade between %s has cancelled because he/she dont have item %s." ]
	TradeTargetNotFound 				= [ "Target player not found, trade cancelled." ]
	NoPendingTrade 						= [ "You dont have any pending trade offer." ]
	TradeCancelManual 					= [ "[#ffffff]%s has rejected trade offer you send." ]
	TradeCancelManual2 					= [ "You reject this trade offer." ]
	TradeSyntax 						= [ "Syntax, /sendtrade [item you offer] [amount] [player] [item you want] [amount]"]
	SetLobbySpawn2 						= [ "You will spawn on spawnloc when joined the server." ]
	SetLobbySpawn4						= [ "You will spawn on spawnloc when joined the server. You can change default location later with /psetting lobbyspawn" ]
	SetLobbySpawn3						= [ "You will spawn on lobby when joined the server. You can change default location later with /psetting lobbyspawn" ]
	Spawnloc2							= [ "Sucessfully set your spawn location." ]
	SetHudType 							= [ "You changed hud style to [#ffffff]%s." ]
	KillReward2							= [ "You has been rewarded [#ffffff]$200 %sfor assist kill [#ffffff]%s." ]
	KillMessage2						= [ "[#ffffff]%s %s+ [#ffffff]%s %shas killed [#ffffff]%s%s. [#ffffff][%s] [%s] [%.4fm]" ]
	EnterWorldBug 						= [ "Cant move? press alt + ctrl and click on the screen." ]
	BroughtVIPPass 						= [ "You purchased an VIP Pass. Active it with /use vippass" ]
	XCoinBuyPass 						= [ "You need 320 Vice Coin to purchase VIP Pass." ]
	BroughtGPass 						= [ "You brought an Gang Creation Pass. Use it with /creategang" ]
	XCoinBuyGPass 						= [ "You need 50 Vice Coin to purchase Gang Creation Pass." ]
	Register2 							= [ "You received [#ffffff]$150,000, 25 Vice Coin, 1 VIP Pass (30days), 1 World Pass, 5 Weapon Name Tags %sas register reward." ]
	GangCreategangSyntax2 				= [ "Syntax, /creategang [tag] [name]" ]
	PickupsomeEdit 						= [ "Someone already edit that pickup." ]
	KillReward5 						= [ "Headshot bonus +[#ffffff]$500" ]
	GiveitemSyntax 						= [ "Syntax, /giveitem [player] [item] [quatity]" ]
	GiveItem 							= [ "You given item %s [#ffffff][%d] %sto [#ffffff]%s" ]
	GiveItem2 							= [ "You received item %s [#ffffff][%d] %sfrom [#ffffff]%s" ]
	SellCoinExeeded						= [ "You cannot give more than $5,000,000 at once." ]
	NotEnoughGiveCash 					= [ "You dont have enough cash." ]
	GiveCash							= [ "You given [#ffffff]$%s %sto [#ffffff]%s" ]
	GiveCash2 							= [ "You received item [#ffffff]$%s %sfrom [#ffffff]%s" ]
	GiveCashSyntax 						= [ "Syntax, /givecash [player] [amount]" ]
	JoinMsg2 							= [ "Welcome back, [#ffffff]%s %s" ]
	ReactionTestStart 					= [ "The first person who types [#ffffff]%s." ]
	ReactionTestEnd 					= [ "Nobody has won the reaction test, a new one will start soon." ]
	ReactionTestWin 					= [ "[#ffffff]%s %shas won the reaction test in [#ffffff]%s." ]

	EventHosteventSyntax 				= [ "Syntax, /hostevent [waterfight] [price]" ]
	EventJoineventSyntax 				= [ "Syntax, /joinevent [waterfight]" ]
	EventWaterFightStart 				= [ "[Water Fight] [#ffffff]%s %shas hosted the event. Type /joinevent waterfight to join the event. Price [#ffffff]$%s" ]
	EventNotEnoughCashToHost 			= [ "You dont have enough cash to host event." ]
	EventNeedAtleast150kToHost 			= [ "Price cannot below than $150,000." ]
	EventWaterFightAlreadyHosted 		= [ "Someone already hosted Water Fight Event." ]
	EventWaterFightJoin 				= [ "[Water Fight] [#ffffff]%s %sjoined the event." ]
	EventWaterFightNoHosted 			= [ "No active Water Fight Event Running. You can host it with /hostevent" ]
	EventWaterFightStarted 				= [ "Water Fight Event already started." ]
	EventWaterFightCanceledNoPlr 		= [ "[Water Fight] Event being cancelled because not enough player." ]
	EventWaterFightRefund 				= [ "You has been refunded because event has been cancelled." ]
	EventWaterFightDeath 				= [ "[Water Fight] [#ffffff]%s %sis out of event!" ]
	EventWaterFightWinner 				= [ "[Water Fight] [#ffffff]%s %swon the event. Reward [#ffffff]$%s %sand [#ffffff]%s XP." ]
	EventWaterFightNoWinner 			= [ "[water Fight] Event has been ended." ]

	ATargetUIDMismatch 					= [ "You cannot login into admin remotely." ]
	NeedAllowLogin 						= [ "You are not allowed login into account from another PC. Contract admin on discord." ]
	GetEventCmd 						= [ "Event commands [#ffffff]/hostevent /joinevent" ]

	CreateGangHelp 						= [ "Type [#ffffff]/cmds gang %sfor available gang commands." ]
	Worldclaimhelp 						= [ "You just purchased this world. Use [#ffffff]/cmds world %sfor available world commands." ]
	Worldclaimhelp1 					= [ "You can add pickup or object or radar blip in this world. Use [#ffffff]/cmds pickup/object/blip %sfor available pickup/object/blip commands." ]
	Worldclaimhelp2						= [ "For mapping keybinds use [#ffffff]/keybinds mapping" ]
	BuyVehicleHelp 						= [ "You can use [#ffffff]/cmds vehicle %sfor available vehicle commands." ]


	GetDMCmd							= [ "Deathmatch commands[#ffffff]/stats /currentstats /spree" ]
	GetWepCmd 							= [ "Weapon commands [#ffffff]/wep /disarm /spawnwep /changewepname /replacewep" ]
	GetItemCmd 							= [ "Item commands [#ffffff]/nuke /inventory /hide /sendtrade /giveitem /givecash /unlockcrate /claimcrate" ]
	GetAccCmd							= [ "Account related commands[#ffffff] /register /login /changepass /changename /cash /buycoin /sellcoin" ]
	GetWorldCmd							= [ "Private world commands[#ffffff] /buyworld /worldsetting /worldkick /worldban /worldunban /worldsetlevel /worldpermission /worldlock /worldann /gotoworld /worldinfo /worldpermission2 /releaseworld /giveworld /worldlevel /worldnamelist /worldgetpermissions /worldgetpermissions2 /myworlds" ]
	GetObjectCmd						= [ "Object commands[#ffffff] /addobject /findobject /objectlist /editobject /editsens /magicstick" ]
	GetPickupCmd						= [ "Pickup commands[#ffffff] /addpickup /editpickup /findpickup /pickuplist /editsens /magicstick" ]
	GetBlipCmd							= [ "Blip commands[#ffffff] /addblip /deleteblip /findblip /bliplist" ]
	GetVehicleCmd						= [ "Vehicle commands[#ffffff] /getveh /buyveh /vehinfo /editvehhandling /releaseveh /parkveh /vehsetting /eject /fix /flip /vehradio /despawnveh" ]
	GetMiscCmd							= [ "Player settings and other commands[#ffffff] /psetting (/pset) /msetting (/mset) /settitle /heal /armour /setactivegang /rank /country /fps /ping /forum /discord /admins /server /keybinds /gettop /hp /arm /accept /reject" ]
	GetLocCmd							= [ "Teleport and location commands [#ffffff] /spawnloc /gotoloc /saveloc /goto /lobby /loc /nogoto" ]
	GetGangCmd							= [ "Gang commands[#ffffff] /creategang /gangsetting /ganginvite /gangkick /gangleave /gangchat /gangmembers /gangpermissions /gangaddrank /gangeditrank /gangeditpermission /ganginfo /gangviewrank /joingang /gangsetplayerrank" ]

	SettitleSyntax 						= [ "Syntax, /settitle [text/none]" ]
	RemoveTitle 						= [ "You removed title on your character." ]
	SetTitleScs 						= [ "You attached text [#ffffff]%s %son your character." ]

	ReactTimeout						= [ "Nobody has won the reaction test, a new one will start soon." ]
	RectWon 							= [ "[#ffffff]%s %shas won the reaction test in [#ffffff]%s %sand won [#ffffff]%s!"]
	RectStart 							= [ "The first person who types [#ffffff]%s %swill earn [#ffffff]%s!" ]

	LevelUp 							= [ "[#ffffff]%s %shas been level up to [#ffffff]%d!" ]
	InfoS2 								= [ "Water Fight Won [#ffffff]%s %sReaction test Won [#ffffff]%s %sTotal spends [#ffffff]$%s %sTotal earns [#ffffff]$%s" ]

	StartExportObj 						= [ "Starting exporting object.. Please wait" ]
	StartExportObjComp 					= [ "Export complete. Your file is on [#ffffff]https://vl.kingofvc.best/%s" ]
	NoObjToExport 						= [ "You cannot export this world object because there is no object placed in this world." ]

	GetTopTeam 							= [ "Top Teams: [#ffffff]%s" ]

	HelpMsgF4 							= [ "Press [#ffffff]F4 %sif you wish return to class selection after died." ]
	F4Pressed 							= [ "You will return to class selection after died." ]

	UseLevelUp 							= [ "You consumed an level up pass." ]
	NewyarReward 						= [ "Merry Christmas and Happy New Year! You are granted VIP rank for 30days and Santa Hat (/use santahat)" ]

	PlayerJoin3							= [ "[#ffffff]%s %shas joined for the first time from [#ffffff]%s." ]

	AdminJoinMsg 						= [ "[#ffffff]%s (%s) %shas join the server." ]

}
